### ISSUE TITLE
before_action instead of after_action for :verify_authorized?

### ISSUE THREAD

**Issue by gabrielecirulli** [varvet/pundit#105]
Hey! I was looking for an alternative to cancan and stumbled on pundit and I'd say it looks very nice. I saw this in the README, though:

> ## Ensuring policies are used
> 
> Pundit adds a method called `verify_authorized` to your controllers. This
> method will raise an exception if `authorize` has not yet been called. You
> should run this method in an `after_action` to ensure that you haven't
> forgotten to authorize the action. For example:
> 
> ``` ruby
> class ApplicationController < ActionController::Base
>   after_action :verify_authorized, :except => :index
> end
> ```

This seems to suggest that authorization checks should only be run after the action. As far as I know (I might be wrong, though), this means that the action would run entirely before the exception is raised, which in turn would mean the changes the user is trying to make would take place, even though they just wouldn't see the results in the server's response.

Wouldn't this give a false sense of security and potentially constitute a security issue?

Wouldn't it be correct to use `before_action` instead?

**Comment by tomekr** [comment]
Hi @jnicklas, I agree with @gabrielecirulli that this method definitely can give a false sense of security. The use of this after_action is a bit confusing/mis-leading. Is the original use case for developers to use this during development only to flag methods that don't call authorize? Is this to catch instances in production that don't call authorize? If the latter is the case, then the vulnerability will still exist for any state-changing controller action. If the former is the case, then does a developer just leave this in their code even though it shouldn't ever have any implications in production code? I went through the same thought process as @gabrielecirulli after reading that section.

I think at the very least, there should be an explicit warning in that section of the README for developers not to rely on this method in production and that state changing actions will persist even after the exception is raised.

**Comment by jnicklas** [comment]
>  Is the original use case for developers to use this during development only to flag methods that don't call authorize?

Yes.

> If the former is the case, then does a developer just leave this in their code even though it shouldn't ever have any implications in production code? 

Yes. Because the whole point is that code changes, and someone else might do something which causes authorization not to be performed. It's a safety net. Removing it removes the safety net.

> This method will raise an exception if authorize has not yet been called.

I'm not really sure how we can make this much clearer. If you actually read this section, I think it's pretty clear what this is for. I'd be open to a PR improving the documentation here if you feel strongly about it.
