### ISSUE TITLE
Pundit + Gems like Devise, "right" way to handle it?

### ISSUE THREAD

**Issue by guareschi** [varvet/pundit#113]
What is the "right" way to handle models/controller policies when these classes come from a gem, like, say, Devise?

Having a solid example for a public auth gem like Devise would make for a great learning experience for those who are a bit more green in ruby and rails.

**Comment by atstockland** [comment]
Putting this in your ApplicationController does the trick too:

  def verify_authorized
    super unless devise_controller?
  end

**Comment by fercreek** [comment]
To me works with `after_action :verify_authorized, except: :index`

**Comment by jasonswett** [comment]
@fangari Is the `except: index` going to apply to most people reading this or is that specific to your situation? I'm concerned that people may copy and paste your line wholesale without realizing that `except: index` is (AFAICT) not a necessary part of the solution and pokes a hole in the intended safety net. Let me know if I'm misunderstanding something.

The version I used was:
```ruby
after_action :verify_authorized, unless: :devise_controller?
```

**Comment by asecondwill** [comment]
now needs to be as follows I think:

`after_action :verify_authorized, except: :index, unless: -> { devise_controller? }`
