### ISSUE TITLE
Authorize matcher for controller specs

### ISSUE THREAD

**Issue by thomasklemm** [varvet/pundit#115]
Here's my wish for easter: The `after_action :verify_authorized` seem to count to lots of folks for more than they are (they are a mere safety net in development to give you a hint that an `authorize` call is missing. These lacking `authorize` calls should never make it to production). How about retiring these filters some day and verifying that an authorization has taken place exactly the way you wish in your controller specs (even if you write them just for this purpose, I think its a legitimate one).

``` ruby
describe CategoriesController, "GET #show" do
  let(:category) { Fabricate(:category) }
  let(:user) { Fabricate(:user) }

  before do
    sign_in :user
    get :show, id: category.id
  end

  it { should authorize(assigns(:category), :show?) } # Look at this beauty!
  it { should authorize(assigns(:comment), :new?) }   # If you need to authorize more than one object

  it { should respond_with(:success) }
  it { should render_template(:show) }
  it { should_not set_the_flash }
end
```

@jnicklas et al. What do you think? Who would like this approach?

**Comment by samnang** [comment]
@thomasklemm it looks interesting, does you end up using this approach in your project?
