### ISSUE TITLE
Access a controller's params hash (or workaround) in a policy

### ISSUE THREAD

**Issue by donpinkus** [varvet/pundit#140]
There may be a really obvious answer, but I'm not seeing it.

In my policy, I need to access the params hash sent with any Rails request.

```
class UploadsController < ApplicationController
  def show
    @upload = Upload.find(params[:id])
    authorize @upload
  end
end 
```

```
class UploadPolicy
  attr_reader :user, :upload

  def initialize(user, upload)
    @user = user
    @upload = upload
  end

  def show?
    @user.has_access || params[:some_override]  # Here is where I need to access my params.
  end
end
```

**Comment by ThinkADRIAN** [comment]
@thomasklemm When I follow your example, I get an error that tells me the object passed to authorize is not a symbol???

**Comment by ce07c3** [comment]
I've created a few wrappers because of the inability to pass simple values on to the policy:

````ruby
class PermissionCheck

  attr_reader(:group, :permission, :target)

  def initialize(permission, options = {})
    @permission = permission
    @group = options[:group]
    @target = options[:target]
  end

end
````

And for the `permitted_attributes`, I am passing in a `context` variable, since I might have to get `permitted_attributes` for searching, or for updating/creating.

**Comment by thenickcox** [comment]
The reason I'm wanting to access the params hash in the policy is to make sure that the `current_user` is the one from the `params`, i.e., that the user with id 2 isn't able to access `/users/1/reviews/new`.

**Comment by vergenzt** [comment]
I'm having the same issue.

**Comment by jakehockey10** [comment]
I love this gem.  LOVE it.  I have only used it in two application so far though, so I'm still learning.

I am using Devise for user sessions and I also have user roles implemented with enums in the model and integers in the db.  I want users that are logged in with sufficient authority defined by their roles to be able to create other users and limit the role they are allowed to bestow on the user they are creating.

What I'd like to be able to do is implement my `UserPolicy` such that the `create?` method only returns true if that user being created does not have too elevated of a role.  I indeed plan on limiting the choice logged in users have in the view, but that doesn't stop the request from being possible.  For example, I want super admins to be able to create admins, but I don't want admins to be able to create super admins.

What could I do in this case with how Pundit work now?

**Comment by imi56** [comment]
@vergenzt @thenickcox  Any magic worked for you?

**Comment by dachinat** [comment]
Hello,

I'm using

```
def banner
    authorize params, :banner,  policy_class: Api::SharedHostingPolicy
end
```

and

```
class Api::SharedHostingPolicy < ApplicationPolicy
  ALLOWED_KINDS = [:light, :dark]

  def banner
    ALLOWED_KINDS.include? record[:kind].to_sym
  end
end
```

Do you know a better way? Thank! 😅

**Comment by dcangulo** [comment]
I don't know if this is better but I did it this way.

In my **app/controllers/posts_controller.rb**

```ruby
class PostsController < ApplicationController
  before_action :check_user

  def index
    @posts = Post.all
  end

  def new
    @post = Post.new
  end

  #OTHER METHODS

  private 

  def check_user
    # params[:key] will pass the 'key' parameter
    # get_method(params[:action]) will return 'index?' or 'new?'
    # get_class(self) will return 'PostPolicy' class, you can add parameter.split('::').last if you have namespaces
    authorize params[:key], get_method(params[:action]), :policy_class => get_class(self)
  end

  def get_class parameter
    parameter.class.to_s.gsub('sController', 'Policy').constantize
  end

  def get_method parameter
    parameter.to_s + '?'
  end
end
```

And in my **app/policies/post_policy.rb**, I have:

```ruby
class PostPolicy < ApplicationPolicy

  def index?
    # record variable contains the key that I passed
    record.present?
  end

  def new?
    # record variable contains the key that I passed
    record.present?
  end

  #OTHER METHODS

end
```

I did it this way to avoid calling `authorize` to every method and be able to pass a variable from the controller to the policy for validation.

**Comment by timdorr** [comment]
For others running into this issue, I solved it with a bit of data cramming in the `pundit_user` method on my ApplicationController. I included some code to make it backwards compatible with my existing specs, but here's what I've got:

```ruby

# /app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  #...

  def pundit_user
    { user: current_user, params: params }
  end

  #...
end

# /app/policies/application_policy.rb
class ApplicationPolicy
  attr_reader :user, :params, :record

  def initialize(context, record)
    if context.is_a?(Hash)
      @user = context[:user]
      @params = context[:params]
    else
      @user = context
      @params = {}
    end
    @record = record
  end
end
```

I think something like a `pundit_context` method would be useful. It could be a third parameter on the initializer. I haven't looked to see if something like this has already been suggested, but I could see it being broadly helpful.
