### ISSUE TITLE
undefined method admin? for nilnilclass

### ISSUE THREAD

**Issue by ryankc33** [varvet/pundit#157]
I've been following This is [guide here](http://thunderboltlabs.com/blog/2013/03/27/testing-pundit-policies-with-rspec/) and been receiving this error message in rspec

```

  context "for a visitor" do
    let(:user) { nil }
    it { should_not permit(:new)    }


     NoMethodError:
       undefined method `admin?' for nil:NilClass
```

for this policy here

```
  def new?
    user.admin?
  end
```

All other specs passed except for this one.
How do I get this spec to pass?

**Comment by mlt** [comment]
Also for the sake of completeness, In Ruby 2.3+, one can use `user&.admin?` http://stackoverflow.com/a/35509145/673826
