### ISSUE TITLE
undefined method 'policy' in view when running RSpec + Capybara test

### ISSUE THREAD

**Issue by beerlington** [varvet/pundit#163]
I have an Rspec (2.14) test that fails when I try using the `policy()` helper in my view. The spec fails saying the policy method is not available. When I view the page in my browser it works fine and I don't get an error. I've never seen something like this happen before where a helper was not available in a spec, so I figured I'd open a ticket in case someone had run into this before.

The error:

```
ActionView::Template::Error:
  undefined method `policy' for #<#<Class:0x0000000ab4ae60>:0x0000000ab4a4d8>
```

Code from my view when it's failing:

``` erb
<% if policy(Subscription::Free.new).create? %>
```

If I update my template to the following it works in both the browser and specs, so I have a workaround, but it's odd.

``` erb
<% if SubscriptionPolicy.new(current_user, Subscription::Free.new).create? %>
```

**Comment by jaykilleen** [comment]
I am having this same issue but on a controller that inherits from `ApplicationController` and in the `ApplicationController` I have `include Pundit`. The only other thing I can add is I am using Draper and the policy method is being called from inside a decorate method on the project class.

**Comment by sbuhr** [comment]
@jaykilleen have you found a solution? I have the same issue when i use shared partials.

**Comment by jaykilleen** [comment]
@sbuhr no I haven't sorry. I have `skip 'undefined method policy issue'`littered throughout all my specs :worried:

**Comment by sbuhr** [comment]
@jaykilleen See this gist:https://gist.github.com/mkhairi/5148a107d2ed2d8d797f PunditViewPolicy did the trick...

**Comment by TheNeikos** [comment]
I also have this problem and would like to *not* have to use a workaround.

**Comment by rylanb** [comment]
Having the same issue as @jaykilleen and @TheNeikos in the Draper decorators. 

undefined method `policy' for #<UserDecorator:0x007f80a3e31dd8>

Frustrating!

**Comment by tirdadc** [comment]
Running into this with a view spec on a new Rails 5 project, trying to determine what's different now.

**Comment by tirdadc** [comment]
Still nothing on this and https://github.com/elabs/pundit/issues/339 was also closed. Is nobody bothering with view specs at this point?

**Comment by adamgall** [comment]
I'm bothering with view specs and have the same issue. New Rails 5 project, current versions of All The Gems.

**Comment by mlabarca** [comment]
Still failing on rails 5.1

**Comment by tpritc** [comment]
Same here

**Comment by rylanb** [comment]
Just to leave a note: https://stackoverflow.com/questions/29298184/why-pundit-cant-find-policies-in-controller-tests/38236956#38236956 may fix it.

**Comment by Dearest** [comment]
same here

**Comment by srshkmr** [comment]
any updates on how to fix this issue?

**Comment by evgenyneu** [comment]
I'm having the same error in Rspec view tests. Any solution to this?

**Comment by philsmy** [comment]
It seems like almost 9 years on this is still an issue. new project, rails 7, view spec...

`undefined method `policy' for #<ActionView::Base`

**Comment by amitpatelx** [comment]
Same issue with Rails 7 in a helper spec for

```
# xyz_helper.rb
def download_link(record)
  link_to(...) if policy([:admin, record]).download?
end
```
with
```ruby
NoMethodError:
   undefined method `policy' for #<ActionView::Base:
```
