### ISSUE TITLE
Best way to use policy_scope with custom query data 

### ISSUE THREAD

**Issue by linhmtran168** [varvet/pundit#164]
Currently, I'm trying to use policy_scope in index (with pagination) and search controller action, but I've found no way to pass additional arguments to pundit scope. My current workaround is manually creating policy scope and resolve them like this

``` ruby
#user_controllers
@users = UserPolicy::Scope.new(current_admin, User.all(page: params['page'], per_page: params['per_page'], sort_by: params['sort_by'], order: params['order'])).resolve
```

``` ruby
#user_policy
class Scope < Struct.new(:admin, :scope)
  def resolve
    if admin.has_permission('index', 'User')
      scope
    end
  end
end
```

User is not an ActiveRecord class, I'm using [Her](https://github.com/remiprev/her) as the ORM to my REST API.
Is there a better way instead of manually initiate scope like this?

**Comment by dukedorje** [comment]
Here's a nice way to semantically limit existing scopes.

```ruby
scope.all.merge(user.companies)
```
