### ISSUE TITLE
Best way to pass an extra object to authorize method

### ISSUE THREAD

**Issue by murdoch** [varvet/pundit#181]
I have nested routes, like: `/foos/1/users`:

```
# users_controller.rb
def index
  @foo=Foo.find(params[:id])
  @users = @foo.users
end
```

I want to reference @foo in my policy, so I've modified my user_policy initialize method to take another argument:

```
  # user_policy.rb
  def initialize(current_user, user, foo=nil)
    @current_user = current_user
    @user = user
    @foo = foo
  end

  def index?
    current_user.foos,include?(foo) 
  end
```

Is this the way we're supposed to do this sort of thing?

Also I suspect this technique is wrong because I can't use the `authorize` method, and instead have to do the following:

```
  after_action :verify_authorized, except: [:index]

  def index
    @users = @foo.users
    raise Pundit::NotAuthorizedError unless UserPolicy.new(current_user, @users, @foo).index?
  end
```

I'd prefer to use `authorize` method in there but the following all fail:

```
authorize current_user, @users, @foo
# throws an argument error

authorize @users, @foo
# throws a type error
```

Is this the wrong way to do things?

**Comment by vedmant** [comment]
It's so much simpler in Laravel, https://laravel.com/docs/5.8/authorization#writing-policies , you just pass any number of arguments to policy method and that's all.
