### ISSUE TITLE
Support custom arguments for policy

### ISSUE THREAD

**Issue by sobrinho** [varvet/pundit#188]
I would to allow only customer's owner to manage profiles (the customer is given by the controller):

``` ruby
class ProfilePolicy
  def initialize(user, customer, record)
    @user = user
    @customer = customer
    @record = record
  end

  def create?
    @customer.owner == @user
  end
end
```

What I'm currently doing is:

``` ruby
class ApplicationController
  def policy(record)
    policy = PolicyFinder.new(record).policy
    policy.new(current_user, current_customer, record) if policy
  end
end
```

If that's correctly, we should add a section on README explaining that.

**Comment by vedmant** [comment]
It doesn't make sense for me, I have many cases when create? method requires another (parent) model to authorize against. Should I just authorize against that parent model policy instead? That looks like a messy approach, what if I have more logic for authorizing child including parent model, how I'm supposed to do so without passing additional params? Passing everything through a user context looks like a messy hack.

**Comment by Linuus** [comment]
@vedmant I say it depends. If it's like in the example above that you have a User and Organization that's always needed, use the UserContext approach.

Can you give an example where you need multiple objects?

Also, see: https://github.com/varvet/pundit#additional-context

> Pundit strongly encourages you to model your application in such a way that the only context you need for authorization is a user object and a domain model that you want to check authorization for. If you find yourself needing more context than that, consider whether you are authorizing the right domain model, maybe another domain model (or a wrapper around multiple domain models) can provide the context you need.
> 
> Pundit does not allow you to pass additional arguments to policies for precisely this reason.

**Comment by vedmant** [comment]
@Linuus For example I have a "board" model that belongs to user, only owner can add posts to the board. In the posts controller new and create methods I do "authorize :post", that logically that I need to use PostPolicy in the PostsContoller, but I can't check if user owns board there unless I pass board model to PostPolicy, which is needed only for create? method. Passing board model in the UserContext doesn't make sense, it has nothing to do with user, furthermore why to write so much code just to pass one param for a single create? method.

**Comment by Linuus** [comment]
How about this:

```ruby
# In controller
@post = Post.new(permitted_params) # Here the board_id is assigned to the post
authorize(@post)

# In policy
record # Is the post
record.board # is the board
```

Doesn't that work?

**Comment by vedmant** [comment]
@Linuus Yes, this works, but this is not obvious, creating model and passing prams through model before saving looks like a workaround, it also will require to change quite much code in my controllers and add new variables. If this is official approach it would be nice to have in the documentation as it's not obvious.

**Comment by Linuus** [comment]
@vedmant That's the idiomatic approach in Rails projects so I don't think we need it in the Pundit docs.

See: https://guides.rubyonrails.org/action_controller_overview.html#parameters
