### ISSUE TITLE
Add namespaces support to documentation

### ISSUE THREAD

**Issue by guzart** [varvet/pundit#373]
Namespaces support was added on #331, however the documentation for that features is missing in the README.

**Comment by jnicklas** [comment]
Yes, we definitely should document this. Do you want to send a PR?

**Comment by JenHomann** [comment]
Is this issue just waiting for a PR with passing tests, as it doesn't look like #410 is currently passing? If so, happy to do my part and get the documentation to reflect this (very helpful) behavior.

**Comment by JenHomann** [comment]
On closer inspection, it seems like the failures here were caused a random infrastructure blip. Can we trigger them to run again, @guzart? If more work is needed at that point, I'd be glad to work on it if need be.

**Comment by guzart** [comment]
Thanks @JenHomann, I've triggered a new build. Test are passing now.
It's worth mentioning that besides #410 there's also #392. 

Note: I won't feel offended if #392 is merged 😉
