### ISSUE TITLE
PolicyFinder to returned different Policies for Instance vs Class records

### ISSUE THREAD

**Issue by byu** [varvet/pundit#381]
Feature request.

I'm noticing that I'm doing quite a bit of instance type checking when working with custom permission checks methods. Eg `record.is_a?(Post)` before calling methods on the record for the actual permission checks.

It would be easier for me to do the check just once in the initializer, eg,

```
def initialize(user, record)
  raise Pundit::NotAuthorizedError, 'Invalid Record Type' unless record.is_a?(Post)
  super
end
```

But that would cause problems for class scoped permission checks such as `create?`.

I'm thinking that having the ability to separate the concerns into two policy classes would make my code more assertive, mentally cleaner?

**Comment by jnicklas** [comment]
Hmm, assertive code is good, I agree. I haven't really thought too much about how Pundit can be made more assertive. I suppose one way is to use the inference backwards, e.g.

``` ruby
def initialize(user, record)
  raise Pundit::NotAuthorizedError, 'Invalid Record Type' unless is_a?(Pundit.policy(record))
  super
end
```

But this is a little silly, imo.

**Comment by scottjacobsen** [comment]
Generally type checking with `is_a?` is a bad code smell.

If you really need a different policy for `authorize(@post)` vs `authorize(Post)` I believe you could do something like this:

```ruby
class Post
  def self.policy_class
    PostClassPolicy
  end

  def policy_class
    PostPolicy
  end
end
```

**Comment by scottjacobsen** [comment]
Re #387
