### ISSUE TITLE
PolicyFinder#param_key does not behave correctly for instances of namespaced classes

### ISSUE THREAD

**Issue by OkayDave** [varvet/pundit#408]
This is something I've come across a couple of times using `permitted_attributes()`. The workarounds are simple enough, so it's not a huge issue, I just wanted to check with you if this is the intended behaviour. If it isn't, I'm more than happy to submit a PR with a fix.

Given a namespaced class and object:

```
class Board::Comment < ActiveRecord::Base
end

@comment = Board::Comment.new
```

The expected `param_key` for `@comment` would be `board_comment` - such as what would be generated in `form_for @comment ...`. 

With `permitted_attributes(Board::Comment)`, the determined `param_key` is correct. However, with `permitted_attributes(@comment)` the determined `param_key` is just `comment`.

This is due to the checks on `object` in  https://github.com/elabs/pundit/blob/master/lib/pundit/policy_finder.rb#L64 - Rails provides the correct `param_key` via `model_name`; however this is only defined as a Class method, not an instance one. If `@comment` is passed, then it will fail the `respond_to?(:model_name)` and fall to the call to `object.class.demodulize.underscore` which will return `comment`.

The reason I'm asking about this first rather than just submitting a PR is that the classes in https://github.com/elabs/pundit/blob/master/spec/spec_helper.rb all define `model_name` as instance methods. I wasn't sure if this was an oversight or an expected implementation detail that I missed. Indeed, the workaround I've been using is to define an instance method:

```
class Board::Comment < ActiveRecord::Base

  def model_name
    @_model_name ||= self.class.model_name
  end

end
```

My proposed fix for this would be to add an additional clause to `PolicyFinder#param_key` to the effect of:

`elsif object.class.respond_to?(:model_name)`

Similar to the clauses in `PolicyFinder#find` and `PolicyFinder#find_class_name`.

**Comment by hd719** [comment]
Hello can I work on this bug?

**Comment by Linuus** [comment]
Closed due to inactivity/can’t reproduce.
