### ISSUE TITLE
Improve error message when constructor takes the wrong number of arguments

### ISSUE THREAD

**Issue by jnicklas** [varvet/pundit#448]
Currently we just raise an `ArgumentError`, but this might not be too easy to understand, since the error originates deep inside Pundit.

**Comment by JIAZHEN** [comment]
@jnicklas Pundit is nice, therefore I am attempting to contribute to the project. Would be nice to have some comments on https://github.com/elabs/pundit/pull/452, thanks!

**Comment by Linuus** [comment]
Closed by #462
