### ISSUE TITLE
Add rspec documentation for scopes

### ISSUE THREAD

**Issue by amingilani** [varvet/pundit#449]
The rspec documentation doesn't include testing for scopes. I recommend examples are added.

I found [these](https://gist.github.com/netzfisch/acc249f828884c739848) tests that checked if posts were published, but in my particular case I was testing for whether users owned the records they were trying to access, so my tests became:

```ruby
# spec/policies/expense_policy_spec.rb
RSpec.describe ExpensePolicy do
  before :each do
    @user = FactoryGirl.create :user
    @user.expenses << FactoryGirl.build(:expense)
  end

  let(:policy_scope) { ExpensePolicy::Scope.new(user, Expense).resolve }

  context 'for the user role' do
    let(:user) { @user }

    permissions '.scope' do
      it 'only shows expenses the user owns' do
        expect(policy_scope).to eq @user.expenses
      end
    end
  end
end
```

The code to pass these tests was simply:

```ruby
# app/controllers/expenses_controller.rb
class ExpensePolicy < ApplicationPolicy
  class Scope < Scope
    def resolve
      return scope.all if user.admin?
      scope.where(user: user)
    end
  end
end
```

**Comment by damien** [comment]
I'm always in favor of better docs. The only suggestion I'd make is to avoid using libraries like FactoryGirl in favor of vanilla ruby whenever possible.

**Comment by ce07c3** [comment]
`return scope if user.admin?` should suffice?

**Comment by seorc** [comment]
I find very useful to have my test user built or created inside of each example, so the name of the var containing it is not necessarily the same. I am using the following technique. Would it be a good example for the docs?

```rb
RSpec.describe PostPolicy do
  subject { described_class }

  def resolve_for(user)
    subject::Scope.new(user, Post).resolve
  end

  permissions '.scope' do
    it 'allows the user to see his posts' do
      usr = User.new
      # Create test Posts here, link one of them to usr
      expect(resolve_for(usr).count).to eq(1)
    end
  end
end
```

**Comment by Linuus** [comment]
I don't think this is needed. There is nothing special with testing pundit scopes. I did merge a PR today which made that clearer in the readme: https://github.com/varvet/pundit#scope-specs

**Comment by amingilani** [comment]
@Linuus oh, I agree there's nothing special about testing with Pundit.

However, since testing is important, IMHO, pundit should totally provide examples about how these can be achieved. Just because it saves new adopters the cognitive load of figuring this out.

**Comment by benoror** [comment]
+1 This example would be great for the docs, [maybe under a doc/ folder, (just as rodauth's)](https://github.com/jeremyevans/rodauth/tree/master/doc), or in GH Wiki?
