### ISSUE TITLE
Problem with nested class

### ISSUE THREAD

**Issue by software-project** [varvet/pundit#450]
I'm working with Rails 5. My policy looks like this:
```
class ModelPolicy < ApplicationPolicy
  class Scope < Scope
    def resolve
      scope
    end
  end

  def index?
    ...
  end
end
```

And I'm getting `NameError: uninitialized constant ModelPolicy::Scope`

**Comment by rystraum** [comment]
`Scope` should also be defined in `ApplicationPolicy` so you can inherit from it.

My `ApplicationPolicy` looks like this: (this was generated by Pundit via `rails g pundit:install`)

```
class ApplicationPolicy
  # all the other methods
  class Scope
    attr_reader :user, :scope

    def initialize(user, scope)
      @user = user
      @scope = scope
    end

    def resolve
      scope
    end
  end
```

**Comment by JIAZHEN** [comment]
You don't have to extend `Scope` for your custom Scope.
```
class ModelPolicy < ApplicationPolicy
  class Scope
  end
end
```
Should work.

**Comment by Linuus** [comment]
I believe this is solved?
