### ISSUE TITLE
PolicyFinder issue when using nested models

### ISSUE THREAD

**Issue by cars10** [varvet/pundit#454]
Hi, we have the following setup:

```ruby
# Controller in controllers/management/foos_controller.rb
class Management::FoosController
...
end
```

```ruby
# Model in models/bar/foo.rb
class Bar::Foo
...
end
```

If i try to authorize a  `foo` in my controller i use the following pundit call: 
```ruby
authorize [:management, foo]
```
Pundit now looks for a policy in `/policies/management/bar/foo`  because it takes the model namespace into account. I want to use a policy in `/policies/management/foo` because that matches my controller structure. Is there a way to solve that?

**Comment by ryanhertz** [comment]
@cars10 Have you tried defining `policy_class` in `Bar::Foo`? https://github.com/elabs/pundit#manually-specifying-policy-classes

Maybe something like this?
```ruby
class Bar::Foo
  def self.policy_class
    name.demodulize + "Policy"
  end

  def policy_class
    self.class.policy_class
  end
end
```

**Comment by cars10** [comment]
No, because i do not want to use the same policy every time i use the model - so that does not work for me.

**Comment by ryanhertz** [comment]
@cars10 I think I discovered a bug that would prevent this from working the way I expected, but I've submmited a fix here - https://github.com/elabs/pundit/pull/475

If that PR is merged, then you should be able to add the `policy_class` methods to `Bar::Foo` like I did above and then you'll be able to control the policy like this:
```ruby
foo = Bar::Foo.new

authorize foo
# FooPolicy

authorize [:management, foo]
# Management::FooPolicy

authorize [:bar, foo]
# Bar::FooPolicy
```
But again, this won't actually work without https://github.com/elabs/pundit/pull/475

**Comment by Linuus** [comment]
For now, if you want to use different policies and not have it matched by the model you'll have to wrap it in another object, do as @ryanhertz proposed above when the bug is fixed, or instantiate the policy manually.
