### ISSUE TITLE
Adding a context for class-based auth?

### ISSUE THREAD

**Issue by smoyth** [varvet/pundit#457]
I have a situation where `:index?` should be granted for `Billing::Account` only in certain contexts (communities, specifically).

This seems like a weak spot for Pundit. The orthodox way to authorize index requests seems to be to do `authorize Billing::Account, :index?`. But there is no way to pass any context other than the user. This is not a problem when you have a specific record since you can dig the needed context out of the record itself.

Sure I could do `Billing::AccountPolicy.new(user, Billing::Account, context: whatever)` and forego the nice DSL and rspec matchers and etc, but that's a big bummer!

Or I guess I could do `dummy_account = Billing::Account.new(community: community)` and then check `index?` on that but that seems kind of hackish...

Would you be open to either allowing an optional options hash in methods like `authorize` and `policy`, OR, adding an overridable `pundit_context` method that fetched the current context much like `pundit_user` fetches the current user? And then passing that context through all the various DSL methods?

Thanks for considering!

**Comment by hooverlunch** [comment]
Having thought about this more I think it's acceptable to use a dummy object. I'll probably need to put a comment explaining it as it is a bit counterintuitive but that's ok!

Thanks for all your great work!
