### ISSUE TITLE
#permitted_attributes should either support STI classes or accept a param_key argument

### ISSUE THREAD

**Issue by johvet** [varvet/pundit#459]
We're using all aspects of pundit in our quite big application and we simply love it. It's simple and very flexible. When we started to use the `#permitted_attributes` the `PolicyFinder` tries to derive the proper `param_key` from the "resource" provided. This works well for most usecases, but for #update actions, when provided a record instance of an STI model, it fails. It would use the `ActiveModel::Name` tied to the child class and thus resolve to the wrong param_key. 

Are there any plans on making this configurable? For example by adding another 3rd argument to `#permitted_attributes` eventually bypassing PolicyFinder or maybe "extend" the PolicyFinder to walk up the STI tree and use the base-classes `model_name`?

We're willing to bring in a PR for either one of the above - or even another approach.
Please advise ;-)

**Comment by Linuus** [comment]
Why is this only a problem with `#update`? The param key is used for other actions as well, right?
I guess you would you be able to use this to fix the issue: #502 if it's merged, right?

**Comment by ce07c3** [comment]
Why nit add more policies for each of the subclasses specifically?

**Comment by Linuus** [comment]
@ce07c3 the `param_key` is not coming from the policy so I don't think that would help here.

https://github.com/varvet/pundit/blob/master/lib/pundit/policy_finder.rb#L64-L72

**Comment by Linuus** [comment]
I will close this for now and refer to the functionality in #502. We can always revisit this in the future if there is need.
