### ISSUE TITLE
Pundit returning wrong scope after devise logout/login

### ISSUE THREAD

**Issue by viamin** [varvet/pundit#470]
I'm using pundit with devise in a Rails 5.1-backed javascript app. I'm seeing strange behavior when testing the following workflow:

1. Log in as an admin user (policy_scope returns everything for a given model)
2. Log out with AJAX request
3. Log in as a regular user with AJAX request

After step 3, my app thinks a regular user is logged in, but policy_scope returns the scope for the admin user.

It looks like the policy_scope helper uses a cached scope from @_pundit_policy_scopes:
pundit.rb:119
```
  module Helper
    def policy_scope(scope)
      pundit_policy_scope(scope)
    end
  end
```
pundit.rb:275
```
def pundit_policy_scope(scope)
    policy_scopes[scope] ||= Pundit.policy_scope!(pundit_user, scope)
  end
```
pundit.rb:257
```
  # Cache of policy scope. You should not rely on this method.
  #
  # @api private
  def policy_scopes
    @_pundit_policy_scopes ||= {}
  end
```

There should be a way to clear the policy scope cache when the user logs out. 

I found another report of this on StackOverflow without an answer, so I'm not the only person to hit this:
https://stackoverflow.com/questions/40793638/pundit-user-does-not-change-user-in-policy-after-devise-sign-out

**Comment by Linuus** [comment]
If someone could create a minimal app which reproduces the issue I'd be very grateful!

**Comment by gkemmey** [comment]
Think this app and running `bundle exec rspec ./spec/controllers/vistors_controller_spec.rb` shows the issue: https://github.com/gkemmey/rails-devise-pundit

**Comment by reedlaw** [comment]
@gkemmey your test is not reproducible when running `rails server` and going through the same steps manually. The memoized `policy_scopes` is not persisted across requests. So I believe this only affects certain environments such as tests.

**Comment by gkemmey** [comment]
@reedlaw Hey been a while, but yeah, I'd only ever seen it on tests. Although, original issue looks like that wasn't the case. Threw up my two cents since googling the issue brought me here 🤷‍♂️

**Comment by Burgestrand** [comment]
This issue is a bit stale. If somebody can reproduce this bug I'd be happy to reopen this issue and hopefully it can be fixed in the future.
