### ISSUE TITLE
We're working on getting back on track

### ISSUE THREAD

**Issue by ingemar** [varvet/pundit#484]
Dear pundit-community,

Sorry for the neglect as of lately! We're working on getting up to speed with current issues and pull requests.

Sincerely,

~ The @varvet team

**Comment by ce07c3** [comment]
@ingemar happy to help if you need more people, have been using Pundit for years now and feeling pretty confident with its code base.

**Comment by fwolfst** [comment]
@ingemar Could you probably just merge e.g. https://github.com/varvet/pundit/pull/466 ? I commented there about different other possibilites on how to improve the README to reduce programmers frustration. Thanks. And there are various people offering you to help (or fork). I think a clear statement from maintainers side is needed - and if varvet cannot maintain it, you guys should still be praised for the great work done so far(!), but then give away control in a fair manner.

**Comment by ingemar** [comment]
@fwolfst I'll take a look at it ASAP

**Comment by ce07c3** [comment]
@ingemar The merge that was done was not a good one imho. The docs did reflect the master branch, if the gem does not reflect the master branch, then that's something a programmer needs to check.

**Comment by ingemar** [comment]
I _personally_ have strong feelings against Pundit, so that's the reason why I'm not taking a lead on this project. We do use it quite extensively at a range of projects here at Varvet (former Elabs). Since Jonas left there hasn't really been a maintainer. The plan was for someone here to carry the torch, but we've been swamped with work.

I'm going to look into if we can promote one or two from the community as collaborators.

**Comment by ce07c3** [comment]
@ingemar I have offered my help multiple times. I don't understand why it's been difficult to accept more maintainers. :)

**Comment by fwolfst** [comment]
Luxury problems ahead :)
@ingemar, @ce07c3  I am happy to see stuff moving. Thanks!
Of course it would be great if the projects maintenance aligns along a professional passion flow, without too much "emotional" frictions.

**Comment by pablocrivella** [comment]
I would also be willing to help :)

**Comment by adibairpr** [comment]
@ingemar Can you elaborate on you having strong feelings against pundit? Do you think it's not futureproof? Or did you just mean you don't want to take a lead on the project yourself? Just looking for clarification, thanks.

**Comment by adibairpr** [comment]
@ingemar Also, I'm not seeing a lot of issues regarding Rails 5 in this gem, so I'm also wondering if it's compatible with Rails 5 as it is? If not are there plans to upgrade it? Thanks.

**Comment by pablocrivella** [comment]
@swrobel Pundit still works great IMHO even with rails 5.2, and it's quite easy to override when needed, but of course it could keep improving and lately it got a bit stuck, but i don't think is abandoned yet :)

**Comment by Linuus** [comment]
I’m currently on parental leave until the end of next week. After that I hope I can get some time to get this project up to speed again.

**Comment by swrobel** [comment]
@Linuus congratulations, and thank you for taking the time out of your leave to drop in and leave that note. Enjoy the rest of your precious time!

**Comment by pablocrivella** [comment]
What about merging efforts with https://github.com/palkan/action_policy from now on?

**Comment by ycherniavskyi** [comment]
Do @varvet team have any rough due date for next version release? The current unreleased changelog already has handy changes and useful fixes, which, as for me, deserve for next version 🙂.

**Comment by Linuus** [comment]
See https://github.com/varvet/pundit/issues/527

In the next few days I’ll release a new version.

**Comment by Linuus** [comment]
Pundit 2.0.0.beta1 has been released: https://rubygems.org/gems/pundit/versions/2.0.0.beta1
