### ISSUE TITLE
One policy for all

### ISSUE THREAD

**Issue by Sahar-Remodeling** [varvet/pundit#495]
I have large number of controllers/module and I need one policy (applicationPolicy) to handle their common actions. Do I need to create a policy class for each controller (record)?

**Comment by wayne5540** [comment]
This might help: https://github.com/elabs/pundit/issues/12#issuecomment-345693675

You can just override `policy(record)` in your ApplicationController

ex:

```ruby
class ApplicationController < ActionController::Base
  #...
  private

  def policy(record)
    ApplicationPolicy
  end
end
```

I opened a PR #497 for that to update this approach on readme as well, hope it could get merged.

**Comment by wayne5540** [comment]
You can simply override `policy(record)`

ex:

```rb
class ApplicationController < ActionController::Base
  include Pundit
  # ...
  private

  def policy(record)
    policies[record] ||= "#{controller_path.classify}Policy".constantize.new(pundit_user, record)
  end
end
```

**Comment by tom-lord** [comment]
...But in general, I *would* recommend creating blank policies for each model.

This makes it clear to other developers that there is no special behaviour (without having to unpick how you've over-ridden the policy class). It also makes the code easy/obvious how to change in future, when special rules do need to apply for a model.

In addition, note that blank policy classes will be _auto-generated_ when you create a new model via `rails generate`.
