### ISSUE TITLE
Silent 'failure' in the case of using a Ruby select enumerator and Pundit 'policy!'

### ISSUE THREAD

**Issue by CharlesMcMillan** [varvet/pundit#496]
We recently migrated from CanCanCan to Pundit, and we just noticed that we ran into the following problem in our code (specifically a serializer downstream from a controller):
```ruby
class SensitiveDataRecord < ActiveRecord::Base
  belongs_to :related_record
  belongs_to :user
end

class RelatedRecord < ActiveRecord::Base
  has_many :sensitive_data_records
end

# example policy
class SensitiveDataRecordPolicy
  class Scope < BasePolicy::Scope
    def resolve
      scope.where(user_id: current_user.id)
    end
  end

  def show?
    record.user_id == current_user.id
  end
end

# vvvvvv Problem demonstration here vvvvvv In a serializer or somewhere else downstream from a controller
def method_to_retrieve_sensitive_data_from_association
  related_record.sensitive_data_records.select do |sensitive_member|
    Pundit.policy!(current_user, sensitive_member)
  end
end

```
You'll notice here that there is a silly mistake here (yet to some people it's actually hidden in plain sight!) in that select is being used with `policy!` without calling a `show?` or any permission defined on the policy, so this ends up being a data leak if we're relying on the `select` to filter out unpermissioned records.

A little context here...in the CanCanCan world, they took what was the method definition of the permission (let's say 'show?') and forced that method into the argument of the permission check, rather than invoking the method directly --> i.e. `Ability.new(current_user).can?(:show, record_to_permission)` The advantage with that is that it avoids the silly mistake that I quoted in the original example since it doesn't require you to invoke a method to get the truthy/falsy result we need (and hence that slightly smaller chance that someone makes a silly mistake). Has there been any thought to providing a method signature to accommodate this? One definitely could make the argument that there are other guards to catch this kind of mistake (specs to confirm correct behavior as an example 😄 ), but it would be also nice if the framework prevented silly mistakes.

Another thing that would understandably jump to mind here would be to just always use `policy_scope` rather than `select...{|x| Pundit.policy!...show? }`. In fact, we do very much prefer to do that; however, in this case, we're quite a bit downstream from our top level query (quite a common example is grabbing associated objects in a serializer that has a has_many relationship to the root `object` being serialized), a `policy_scope` actually creates an 'n+1' situation, since we are no longer able to leverage what we preloaded earlier in the request.

**Comment by Linuus** [comment]
If I understand correctly you fetch all data and then try to filter it in ruby for the current user? Why don't you have a query that fetches the correct data for that user from the beginning? It seems a bit weird to carry around a bunch of data that the user isn't allowed to see anyway and filter it out at the end.

I don't think this is an issue with Pundit.
