### ISSUE TITLE
Patterns for using with serializers

### ISSUE THREAD

**Issue by oyeanuj** [varvet/pundit#498]
Hi everyone! In my code, I find myself struggling with finding a good pattern of using Pundit in conjunction with serializers (AMS 0.9 to be precise) in one particular case. Let's say I have a `User` model and based on who is seeing it, different attributes of the model get passed through. Here is a simplified example of the solution I've pieced together:

```rb
class V1::UserController < ApplicationController

  def show
   render json: @user
  end

end

class UserSerializer < ActiveModel::Serializer
     # ..attributes comes here

	def filter(keys)
		if scope && scope.is_admin?
			keys
			
		else
			keys - [:phone, :address]

		end
	end
end
```

The problem is this feels like duplicating logic that should ideally be inside my Pundit Policy. So, I am wondering if there are patterns or recommendations on to do achieve this by leveraging Pundit more?

Thank you!

**Comment by ksolo** [comment]
@oyeanuj 
I believe what you are looking for is outline here: https://github.com/#manually-retrieving-policies-and-scopes

This will let you access Pundit in your Serializer class giving you reuse I think you are going for in this context.

**Comment by oyeanuj** [comment]
@ksolo Thanks for the tip! So, if I understand correctly, in the serializer, I could just call on the appropriate method in the policy and have it generate the keys/object rather so that source of truth stays there?

**Comment by oyeanuj** [comment]
@ksolo Just checking if you could confirm my understanding of your response?

**Comment by heratyian** [comment]
> @oyeanuj I believe what you are looking for is outline here: https://github.com/#manually-retrieving-policies-and-scopes
> 
> This will let you access Pundit in your Serializer class giving you reuse I think you are going for in this context.

[https://github.com/varvet/pundit#manually-retrieving-policies-and-scopes](https://github.com/varvet/pundit#manually-retrieving-policies-and-scopes)
