### ISSUE TITLE
|| is not recognized as replacement for "or" operator.

### ISSUE THREAD

**Issue by richjdsmith** [varvet/pundit#504]
With Devise, Rolify and Pundit on Rails 5.2, I am running into the issue where when I use the || operator instead of using `or` it does not validate the second part of the or statement.

Example (show method):

```
class UserPolicy
  attr_reader :current_user, :model

  def initialize(current_user, model)
    @current_user = current_user
    @user = model
  end

  def index?
    @current_user.has_role? :admin
  end

  def show?
    @current_user.has_role? :admin || @current_user == @user
  end

  def update?
    @current_user.has_role? :admin or @current_user == @user
  end
...
end
```

In this example, the update method works, but the show method does not.

**Comment by pablocrivella** [comment]
@richjdsmith I don't think this is related to the gem:

Check: 

- https://www.rubytapas.com/2013/08/15/episode-125-and-or
- https://stackoverflow.com/questions/2083112/difference-between-or-and-in-ruby

**Comment by mateusmedeiros** [comment]
@pablocrivella is right.

The line you wrote
```ruby
@current_user.has_role? :admin || @current_user == @user
```

is interpreted by ruby as

```ruby
@current_user.has_role?(:admin || @current_user == @user)
```
That's why it looks like the second part of the condition is never called.

**Comment by pablocrivella** [comment]
@richjdsmith Could you close this issue since this indeed is not related to the gem?

**Comment by richjdsmith** [comment]
Sorry about that, I missed this in my notifications! 

I will close this as that makes perfect sense. 

Cheers all for your help!
