### ISSUE TITLE
Feature request - manually specifying the policy class when calling authorize.

### ISSUE THREAD

**Issue by maxcal** [varvet/pundit#506]
I would like to have the signature of the `authorize` method altered to:

```RUBY
authorize(record, query = nil, policy_class: nil)
```
Lets say I have your classic case where you have a `UsersController` where users have can manipulate their own user records and I have a `Admin::UsersController` where admins can edit other users.

Since pundit derives the policy class from the model both calls to `authorize @user` would use `UserPolicy` and I would have to handle both cases from the same policy class. But that can get messy as the policy may not know the context of the request.

What I want instead is to be able to call:

```RUBY
authorize(@user, policy_class: Admin::UserPolicy)
```

I'm currently using a kludge which reimplements the entire method:

```RUBY
def my_authorize(record, query = nil, policy_class: nil)
  # bail early and defer to default implementation
  return authorize(record, query) unless policy_class
  query ||= params[:action].to_s + "?"
  @_pundit_policy_authorized = true
  policy = policy_class.new(pundit_user, record)
  unless policy.public_send(query)
    raise NotAuthorizedError, query: query, record: record, policy: policy
  end
  record 
end
```

**Comment by pablocrivella** [comment]
@maxcal  I think this is what you are looking for: https://github.com/varvet/pundit/pull/441

**Comment by maxcal** [comment]
Thanks @pablocrivella.
