### ISSUE TITLE
Accessing policy method outside controller throws NoMethodError

### ISSUE THREAD

**Issue by oyeanuj** [varvet/pundit#507]
Hi folks, Based on this [documentation in the README](https://github.com/varvet/pundit#manually-retrieving-policies-and-scopes),  I was trying to access the policy scope from within a serializer but I was getting `NoMethodError`.

```sql
Pundit.policy_scope!(Member.first, Member)
  Member Load (0.5ms)  SELECT  "members".* FROM "members" ORDER BY "members"."id" ASC LIMIT $1  [["LIMIT", 1]]
NoMethodError: undefined method `[]' for #<Class:0x00007f9e7ece6188>
from /Users/anuj/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/activerecord-5.1.6/lib/active_record/dynamic_matchers.rb:22:in `method_missing'
```

`Scope` does exist as part of the MemberPolicy, so I am not sure what might be going on? Not sure if this is a bug in the code or if I was doing something wrong, so I figured creating this issue would be appropriate.

Thanks!

**Comment by Linuus** [comment]
I don't think this is an issue with Pundit. Please re-open if you think otherwise.

**Comment by oyeanuj** [comment]
@Linuus The scope is a `Member` (object) and the policy is below. From what I could dig, it seems to be Pundit related since `MemberPolicy` does have `Scope` declared. Thoughts?

```rb
class MemberPolicy < ApplicationPolicy

  def is_self?
    user == record
  end

  def can_edit?
    user && (is_self? or privileged?)
  end

  def can_view_all?
    user && (is_self? or privileged?)
  end

  def is_admin?
    user && user.member_roles.exists?(role: 'admin')
  end

  def if_visible_to_user?
    privileged? || !record.suspended
  end

  class Scope < ApplicationPolicy::Scope

    @record = @scope

  
    def is_self?
      user == @record
    end

    def can_edit?
      user && (is_self?  or privileged?)
    end

    def can_view_all?
      user && (is_self?  or privileged?)
    end

    def resolve

      @record = scope[:record]
      info_method = scope[:info_method]
      filter_scope = 'viewable_by_world'

      if can_view_all?
        filter_scope = 'viewable_by_author'

      elsif user.present?
        filter_scope = 'viewable_by_user'

      end

      @record.send(info_method).send(filter_scope)

    end

  end
end

```

**Comment by Linuus** [comment]
It looks like you are passing `Member` as the scope and then run `@scope[:record]`, effectively running `Member[:record]`. That seems wrong?
