### ISSUE TITLE
Any chance of a pushing a new gem?

### ISSUE THREAD

**Issue by murdoch** [varvet/pundit#515]
Hi folks, 

The latest gem on rubygems is a bit old, and there's a bunch of cool stuff added since then.
For instance, the latest gem on rubygems forces the following coding style:

```
@posts = Post.all
authorize @posts
```

Whereas if your Gemfile pulls from master branch, then you can do the following:

```
@posts = authorize Post.all 
```

Pardon me if I'm wrong about that.

**Comment by Linuus** [comment]
You are correct.

Changing the return value is a breaking change though so I need to release 2.0 for that. I want to get a few other fixes in 2.0 as well but it will probably be done soon. There is a 2.0 milestone.
