### ISSUE TITLE
Generator is not working?

### ISSUE THREAD

**Issue by chiperific** [varvet/pundit#520]
`$ bundle show pundit`
`> /Users/[me]/.rvm/gems/ruby-2.4.4/gems/pundit-1.1.0`
`$ rails g pundit:install`
`> Could not find generator 'pundit:install'. Maybe you meant 'devise:install', 'rspec:install' or 'responders:install'`

**Comment by Linuus** [comment]
Are you using master or the version on rubygems?

**Comment by chiperific** [comment]
Rubygems

**Comment by chiperific** [comment]
So, I swear I tried un-installing and re-installing the gem before I posted this.

But, I just did it again and now the generator works...sorry.

**Comment by Linuus** [comment]
No worries. I’m glad it worked out :)
