### ISSUE TITLE
Inheritance issue

### ISSUE THREAD

**Issue by CyberMew** [varvet/pundit#524]
I have 3 classes, `BackendUser` and `FrontendUser` and `User`. Both the former inherits from `User`

```
class BackendUserPolicy < ApplicationPolicy
    def login?
        # my code here
    end
end
```
```
class FrontendUserPolicy < ApplicationPolicy

end
```
The above is my current policy codes. Both users can reset their passwords. I would like to have a `UserPolicy`, so that I don't have to copy and paste the same code in both policy files. I would like to have something like this:
```
class UserPolicy < ApplicationPolicy
    def reset_password
        # my code here
    end
end
```
```
class BackendUserPolicy < UserPolicy
    def login?
        # my code here
    end
end
```
```
class FrontendUserPolicy < UserPolicy

end
```
and have `BackendUserPolicy` and `FrontendUserPolicy` to both inherit from `UserPolicy` so that any policies not defined will be called by `UserPolicy`. I tried to inherit from `UserPolicy` but it still can't find `reset_password` as one would thought it would. Is there a way to do something like that? I am calling `authorize @user` in the `users_controller` file. Thank you.

**Comment by Linuus** [comment]
That should work fine.

What do you mean that it can't "find" the `reset_password` method? Is the action you are authorizing called `reset_password`? If so, the method in you policy should be called `reset_password?` (note the question mark at the end).

Could that typo be the issue?

**Comment by CyberMew** [comment]
Yes! The typo was the issue, I figured it out almost immediately after I took a break 😆 🤦‍♀️ 🤦‍♂️  Came back to update my post and you already found my rookie mistake! Thank you.

**Comment by Linuus** [comment]
No worries, it can happen to anyone :)
