### ISSUE TITLE
Pundit generators aren't working in Rails 5

### ISSUE THREAD

**Issue by Jaco-Pretorius** [varvet/pundit#526]
I just started using Pundit on a new Rails 5 project and it looks like the generators aren't being picked up by Rails. 

```
rails g pundit:install
Could not find generator 'pundit:install'. Maybe you meant 'rspec:install', 'devise:install' or 'responders:install'
Run `rails generate --help` for more options.
```

Also, if I list the generators (`rails g --help`) pundit doesn't show up. I'll investigate further, but I just wanted to log it in case someone else has a fix or runs into the same problem.

**Comment by Jaco-Pretorius** [comment]
Ok, did some more digging and it looks like the problem was with spring. I did `spring stop` and then the generators started showing up.

Sorry for the noise!

**Comment by raj2033** [comment]
@Jaco-Pretorius  i tried `spring stop` and retried `rails g pundit:install` but it did not work for me. Is there anything i am missing?

**Comment by raj2033** [comment]
i was directly running the command, without adding to gemfile, expecting it to install itsef, sorry my mistake. 
1. in gemfile: gem 'pundit', '~> 2.1.0'
2. in application_controller 
```
class ApplicationController < ActionController::Base
  include Pundit
end
```
3. then ran the command, it worked

```
user@user-dell >> repo >> feature/authorization >> rails g pundit:install
Running via Spring preloader in process 7340
      create  app/policies/application_policy.rb
```

**Comment by Jaco-Pretorius** [comment]
👍

**Comment by prtk418** [comment]
Got the same error in Rails 6, stopping spring worked for me.
