### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by arpitchauhan** [varvet/pundit#527]
The last release `v1.1.0` was done more than two years ago. There has been substantial development after that release (e. g. `authorize` now returns a record instead of `true`).

Wouldn't it be good to make a new MINOR (or maybe MAJOR) release?

I'd love to use that in my project instead of pointing to the master branch of the repo. 😄

**Comment by Linuus** [comment]
Hi!

I'm working on a new release which will be 2.0 since it has breaking changes. These breaking changes is the main reason I can't release a minor version.

There are only a few things left before I can cut the new release. I know it's long overdue, but it's coming. Please be patient :)

Thanks!

**Comment by arpitchauhan** [comment]
Sure. In case you need any help, let me know!
