### ISSUE TITLE
Access params hash in controller 

### ISSUE THREAD

**Issue by ivanelrey** [varvet/pundit#528]
I am using **ajax-datatables-rails** gem which requires me to pass params hash to a class.

```
def index
  respond_to do |format|
    format.html
    format.json { render json: UserDatatable.new(params) }
  end
end

```
I get the following error:
NoMethodError (undefined method `params' for <ActionController::Parameters:0x007fe167162c90>):

Is there any way to configure pundit so I can access params in a specific method?

**Comment by Linuus** [comment]
I don’t understand what this has to do with pundit?

I think the problem is in your UserDatatable class.

**Comment by ivanelrey** [comment]
Yes correct, my fault. thanks.

**Comment by BSorbus** [comment]
Btw, how use Pundit Scope with ajax-datatables-rails gem?

**Comment by ivanelrey** [comment]
@BSorbus This is what I did:

UserPolicy::Scope.new(@current_user, User).resolve

**Comment by Linuus** [comment]
@ivanelrey Is there a reason you can't just do `policy_scope(User)` instead?

**Comment by ivanelrey** [comment]
@Linuus As I remember I couldn't use policy_scope(User) in UserDatatable class because **current_user** was undefined.

**Comment by ivanelrey** [comment]
@BSorbus 
You need to use policy_scope on the Project table.

Try something like this:
1) Include pundit in your class
    `include Pundit`

2) In your get_raw_records method try:
  `ProjectPolicy::Scope.new(**@current_user**, User).resolve.joins(:user)`

If you get error that the current_user is undefined:
Try in your controller:

`format.json{ render json: ProjectDatatable.new(view_context, user: current_user) }`

and override the initializer of your ProjectDatatable class
  ```
def initialize(params, opts = {})
    @current_user = opts[:user]
    super
  end
```

**Comment by BSorbus** [comment]
**@current_user** ?
2 x * (star) pre and post @current_user?
:O

**Comment by BSorbus** [comment]
Thanks
