### ISSUE TITLE
Pundit 2.0.0.beta1 has been released

### ISSUE THREAD

**Issue by Linuus** [varvet/pundit#533]
Pundit 2.0.0.beta1 has been released: https://rubygems.org/gems/pundit/versions/2.0.0.beta1

Please report any issues you find. If there are no major issues in a while I'll release a stable version.

**Comment by vpereira** [comment]
when are you planing to make a stable version release?

**Comment by Linuus** [comment]
I’ll try and release it at the end of the week.

**Comment by DrewBe121212** [comment]
Hi,

Are there breaking changes with this? I seem to be unable to find the docs/api.

**Comment by Linuus** [comment]
See the changelog: https://github.com/varvet/pundit/blob/master/CHANGELOG.md#200beta1-2018-07-04

**Comment by nicholaspufal** [comment]
Suggestion: don't put a beta version on `master` until it's released. I've had a hard time to understand why `policy_class:` was not working as it was getting listed part of the docs in `master`. Turns out it's a `2.0.0.beta1` feature and not part of the latest stable, `1.1.0`.

Thanks for working on this, pundit is awesome :)

**Comment by Linuus** [comment]
The master branch is where development happens. So the readme will reflect the current work in the master branch. Please select the tag for the version you are using to see a readme for that specific version.

Thank you and you are welcome 😊

**Comment by vpereira** [comment]
> I’ll try and release it at the end of the week.

like today? :)

**Comment by Linuus** [comment]
Nagging is not the way to get a release quicker.

**Comment by Linuus** [comment]
Pundit 2.0.0 has now been released.

https://rubygems.org/gems/pundit/versions/2.0.0
