### ISSUE TITLE
authorize returns true instead of the object

### ISSUE THREAD

**Issue by chris-roerig** [varvet/pundit#534]
Hi. According to the docs 

> `authorize` returns the object passed to it

In practice it's returning `true` for me. Is this the desired behavior?

**Comment by Linuus** [comment]
You are probably using version 1.1 from rubygems? That version didn’t include that change. You need to use 2.0.0.beta1

**Comment by chris-roerig** [comment]
Is that a branch someplace?

**Comment by Linuus** [comment]
It’s the same as master currently. There is also a tag for it. It’s also on rubygems :)

https://rubygems.org/gems/pundit/versions/2.0.0.beta1

Please check the changelog for changes. Since this is a major update it includes breaking changes.
