### ISSUE TITLE
Documented use of `permitted_attributes` helper does not work in Rails 5.1

### ISSUE THREAD

**Issue by greatseth** [varvet/pundit#535]
**What did I do?**

The documentation shows examples of using the `permitted_attributes` helper similar to this statement from an app I was upgrading from Rails 5.0 to Rails 5.1:

`params.require(:user).permit(permitted_attributes(@user))`

**What did I expect to happen?**

In Rails 5.0, statements like this work as documented. When upgrading to 5.1, I found no related Pundit updates, so I expected those statements to continue to work.

**What happened instead?**

In Rails 5.1, I was seeing updates using the helper in this way fail with logging implicating illegal params. The situation doesn't seem to trigger any exceptions or warnings.

My first workaround, once I realized `permitted_attributes` was returning an `ActionController::Parameters` instance, was to call `#keys` on that instance. This gets around the problem but is not ideal.

Eventually I connected the fact that `permitted_attributes` was returning what I needed for the database update and wondered why I was using it in the way I was. The answer is simply that the docs suggested that was how to do it, and I hadn't looked at what `permitted_attributes` provides until today). So, something like this seems to work: `@user.update(permitted_attributes(@user))`.

So, I think the fix is mainly to update the documentation, but I didn't know if the nature of this might prompt some other considerations. It seems odd to me that the documented use of `permitted_attributes` worked in Rails 5.0 but doesn't in 5.1. I'm guessing it has to do with the removal of a `method_missing` proxy for `Hash` methods called on an instance of parameters, but I didn't dig too deep.

**Comment by greatseth** [comment]
Powered by post-issue-publishing anxiety, I now notice that I didn't quite read the docs close enough, and they do show an example like the one I came around to. However, they also show the definition of a controller helper method for providing params which uses a statement similar to the one I began to have problems with.

**Comment by Linuus** [comment]
Where does the documentation say that you can use `permitted_attributes` like that?

The only thing I find in the readme is this:

```ruby
params.require(:post).permit(policy(@post).permitted_attributes)
```

Note that it fetches the policy and then calls `permitted_attributes` on the policy. Now, to make this simpler, you can call the `permitted_attributes` _helper_ in the controller which essentially does the above call for you.

**Comment by greatseth** [comment]
I'm not sure. Perhaps I saw the statement you referenced and somehow drifted to the form I reported about. It still seems odd that the code I reported seems to work before Rails 5.1, but I guess there is nothing to do on this specific ticket. Thanks.
