### ISSUE TITLE
policy_scope retruns error when using Policy Namespacing

### ISSUE THREAD

**Issue by SalmaNegm** [varvet/pundit#539]
I have a Category model which has two scopes. I used Policy Namespacing to differential between the policies of each scope. Unfortunately, when I call policy_scope as mentioned in the documentation `policy_scope([:category, Category.all.order(:id).page params[:page]])` it returns this error message

undefined method `displayable' for #<Array:0x007f9862eacc00> Did you mean? display

this is my Policy file

```
class Category::CategoryPolicy < ApplicationPolicy
    def index?
        @user.has_role? :super_admin
    end

    def create?
        @user.has_role? :super_admin
    end

    def update?
        @user.has_role? :super_admin
    end

    def destroy?
        @user.has_role? :super_admin
    end

    class Scope < Scope
        def resolve
            scope.displayable
        end
    end
end

```

**Comment by Linuus** [comment]
What version of pundit are you using? I suspect that you use 1.1. Please update to 2.0 if so.

**Comment by rsmithlal** [comment]
I occasionally get this same problem using Pundit 2, except in my case the scope (class method) that is not found is being called on an actual AR relation for the scoped model instead of an array. Perhaps it has something to do with the fact that the scope in question, `visibility_public` is generated from a Rails Enum declaration?

```
 enum visibility: {
    visibility_organizer: 0,
    visibility_private: 1,
    visibility_public: 2
  }
```

```
ActionView::Template::Error (undefined method `visibility_public' for #<CallForSubmission::ActiveRecord_Relation:0x00007f442c1e6398>):
    1: 
    2: <% if viewable_calls_for_submissions? %>
    3:   <% cfs = pundit_policy_scope(::CallForSubmission) %>
    4:   <li id="toolbar-item-cfs" class="<%= 'active' if nav_element_active?(
    5:         page: :call_for_submissions,
  app/policies/call_for_submission_policy.rb:9:in `resolve'
```
```
class CallForSubmissionPolicy < ApplicationPolicy
  class Scope < Scope
    def resolve
      scope.visible.visibility_public.available_now
    end
  end
end
```

**Comment by Linuus** [comment]
Can you create a minimal project somewhere which has this issue?
