### ISSUE TITLE
policies not in the default folder app/policies

### ISSUE THREAD

**Issue by aponsin** [varvet/pundit#543]
Hi,

My entire app is namespace to avoid potential conflict with another engine.

So my policies folder is located like this:

`app/myapp/myapp/policies` like the rest of the app, for instance: `app/myapp/myapp/models`, etc.

Everything works fine when I specify the Policy class manually:

```
field :my_field, Objects::MyField, null: false, authorize!: true, policy: ::MyApp::Policies::MyFieldPolicy, description: "Get a single field" do
  argument :id, String, required: true
end
```

But when I try to let the Policy finder do its job:

```
field :my_field, Objects::MyField, null: false, authorize!: true, description: "Get a single field" do
  argument :id, String, required: true
end
```

Well...

```
Pundit::NotDefinedError (unable to find policy `MyApp::GraphQL::Types::MyFieldPolicy` for `#< MyApp::GraphQL::Types::MyField:0x00007f9045cfe3b0 @object=nil, @context=#<Query::Context ...>>`):
```

Not sure how to go about this, I would like to avoid monkey patching the `PolicyFinder`

**Comment by aponsin** [comment]
Well, I finally figured it out... 

Creating a class method in my class: `MyApp::GraphQL::Types::MyField` to specify which policy class to use:

```
    def self.policy_class
      ::MyApp::Policies::MyFieldPolicy
    end
```

**Comment by Linuus** [comment]
Usually when having engines you structure the engines in `apps/myapp/` so the policies would be in `apps/myapp/policies/myapp/some_policy.rb`.

With the structure you have, Rails autoloading fails. I guess you need to call your policy `Myapp::Myapp::Policies::MyFieldPolicy` if you want to keep it like this.
