### ISSUE TITLE
rescue error Pundit::NotDefinedError Exception on method `policy(object).action?`

### ISSUE THREAD

**Issue by marcioJesus** [varvet/pundit#545]
Hello,
I overwrited the namespace policies of methods `policy_scope` and `authorize` and this is ok.

But when I call the method `policy(object).action?` an exception Pundit::NotDefinedError Exception is raised and when I call the method forcing overwrite of namespace `policy([:main, object]).action?` her runs.

@varvet can help in this case?

**Comment by Linuus** [comment]
Please show the code you have problems with.

Overriding `authorize` and `policy_scope` has nothing to do with the `policy` helper. Do you want to have the `policy` method always adding the namespace as well? Then you need to override that as well.

**Comment by marcioJesus** [comment]
Yes, I would like to be able to override the `policy` method in the same way as the `authorize` and  `policy_scope` methods as in this example https://github.com/varvet/pundit#policy-namespacing.

Now a solution to override the namespace in all `policy` calls works but it's a lot of effort
