### ISSUE TITLE
Supporting controller related polices 

### ISSUE THREAD

**Issue by fanantoxa** [varvet/pundit#546]
Hello. Pundit is very good tool but it focus only on Models.
I have a case when I need to have a different polices depend on controllers too instead just models.
Maybe you'll find this case useful too and update Pundit to have it from the box.
For now I've fixed it with overriding `authorize` method in `ApllicationController`:
```
def authorize(record, query = nil)
  super(record, query, policy_class: "#{controller_name.camelcase}Policy".safe_constantize)
end
```
Or maybe you can add method like `authorize_controller` so it'll check depend on controlled?

I that good idea or I can do it in a different way?

**Comment by fanantoxa** [comment]
@Linuus Is it also doesn't work with Pundit ideology?

**Comment by Linuus** [comment]
Hi!

No, I don't think we should have this in Pundit. It's easy enough to override _if_ you want this behaviour. Especially now when people can find this nice Issue you created so thank you for that 😄 👍
