### ISSUE TITLE
Better Exception on #policy_scope

### ISSUE THREAD

**Issue by nicolas-brousse** [varvet/pundit#548]
Hey.

We use `pundit` for a project and we've got an Exception which was confusing.

So we have a Policy with a Scope. And in the scope we did something wrong on a query. The query thrown an exception, and it was an ArgumentError too. But pundit catch it and returned an other exception who wasn't really linked to.

I guess the [`#policy_scope`](https://github.com/varvet/pundit/blob/f6bf57b1b69eb6c859b1a0adb9ba2922a02e4461/lib/pundit.rb#L85) method could be:

```ruby
    def policy_scope(user, scope)
      policy_scope = PolicyFinder.new(scope).scope
    rescue ArgumentError
      raise InvalidConstructorError, "Invalid #<#{policy_scope}> constructor is called"
    else
      policy_scope.new(user, pundit_model(scope)).resolve if policy_scope
    end
```

or 

```ruby
    def policy_scope(user, scope)
      begin
        policy_scope = PolicyFinder.new(scope).scope
      rescue ArgumentError
        raise InvalidConstructorError, "Invalid #<#{policy_scope}> constructor is called"
      end

      policy_scope.new(user, pundit_model(scope)).resolve if policy_scope
    end
```

**Comment by Linuus** [comment]
Yes, it looks like this could be improved. I guess you want to to everything but the `.resolve` within the being/rescue block though. It's this `policy_scope.new(user, pundit_model(scope))` call that we want to rescue if it fails.

**Comment by Linuus** [comment]
Go ahead 👍

**Comment by nicolas-brousse** [comment]
Okay. I'll try to found some time this week and let you inform 😄

**Comment by nicolas-brousse** [comment]
I opened #550
