### ISSUE TITLE
Issue with overriding `policy_class`

### ISSUE THREAD

**Issue by morriskimani** [varvet/pundit#549]
According to the docs, it should be possible to override `policy_class` when calling `authorize`. Instructions from Readme pasted below:
> You can pass an argument to override the policy class if necessary. For example:
```ruby
def create
  @publication = find_publication # assume this method returns any model that behaves like a publication
  # @publication.class => Post
  authorize @publication, policy_class: PublicationPolicy
  @publication.publish!
  redirect_to @publication
end
```

Following these instructions, I've done something similar:
```ruby
authorize(@organization, policy_class: SubscriptionPolicy)
```
But I get the following error:
```
TypeError: {:policy_class=>SubscriptionPolicy} is not a symbol nor a string
from .../.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/pundit-1.1.0/lib/pundit.rb:196:in `public_send'
```
My environment:
Ruby: 2.5.0
Rails: 5.1.4
Pundit: 1.1.0

**Comment by Linuus** [comment]
You need to upgrade to Pundit 2.0

**Comment by morriskimani** [comment]
That fixed my issue. Thanks

**Comment by Linuus** [comment]
No. Well you can call the policy explicitly.

**Comment by javierojeda94** [comment]
Never worked :/ upgrading is not an option

**Comment by Linuus** [comment]
@javierojeda94 What do you mean it "never worked"? Of course it does :) It's just initializing a new object.

Can you show me the code that never worked?
