### ISSUE TITLE
Unexpected behavior for namespaced policies using permitted attributes

### ISSUE THREAD

**Issue by joerodrig** [varvet/pundit#551]
I am currently working with a tool that has a namespaced 'Admin' controller. When using namespaced policies for this admin section, the permitted attributes functionality isn't working as I'd expect. 

In the readme for namespacing, it's suggested you do the following:
```ruby
# app/controllers/admin_controller.rb
class AdminController < ApplicationController
  def policy_scope(scope)
    super([:admin, scope])
  end

  def authorize(record, query = nil)
    super([:admin, record], query)
  end
end

# app/controllers/admin/posts_controller.rb
class Admin::PostController < AdminController
  def index
    policy_scope(Post)
  end

  def show
    post = Post.find(params[:id])
    authorize(post)
  end
end
```

I've attempted to further expand that by using permitted_attributes with authorizations in the Admin Post controller:
```ruby
# app/controllers/admin/posts_controller.rb
  def update
    post = Post.find(params[:id])
    authorize(post)
    ...
    if post.update(permitted_attributes(post))
    ...
  end
end
```

Since the base AdminController sets the policy scope to `:admin`, calling authorize in the pundit `update?` method works fine for a post because the scope is set to look in the admin policy namespace(`app/policies/admin/post_policy.rb`) against an update block.

The permitted_attributes method appears to ignore that scope set though, and pulls the scope from [the record itself](https://github.com/varvet/pundit/blob/f6bf57b1b69eb6c859b1a0adb9ba2922a02e4461/lib/pundit.rb#L262). Since the Post record is not being queried under the 'Admin' namespace(ie. Admin::Post.find(id)), the permitted_attributes method looks in the base PostPolicy file(`app/policies/post_policy.rb`)

Example:
```ruby
# app/policies/admin/post_policy.rb
class Admin::PostPolicy < ApplicationPolicy
  def update?
    puts "This code will be hit"
  end

  def permitted_attributes
      puts "This code wont be hit"
  end
end

# app/policies/post_policy.rb
class PostPolicy < ApplicationPolicy
  def update?
    puts "This code wont be hit"
  end

  def permitted_attributes
    puts "This code will be hit"
  end
end
```

Is this the intended behavior for the permitted_attributes helper? I would have assumed
its scope would also be set by the Admin::PostPolicy scope, and not the record's default PostPolicy scope.

**Comment by Linuus** [comment]
Hi!

Yes, the overrides in `policy_scope` and `authorize` will not affect `permitted_attributes`. You could always override that method as well to force it to add the `:admin` namespace as well.

Will that work for you?

**Comment by Linuus** [comment]
I'll close this for now. Please reopen if you have further questions.
