### ISSUE TITLE
Is there any way to use scopes with headless policies? 

### ISSUE THREAD

**Issue by ahmadabdelhalim** [varvet/pundit#556]
I've been trying to use scopes with a headless policy, but still no luck. I'm not sure if it can be done or not. Is there any way to do that?

**Comment by Linuus** [comment]
It shouldn’t be any different from other policies/scopes. 
What issues do you have?

**Comment by ahmadabdelhalim** [comment]
It keeps telling me that there's no policy with that name. It reads the symbol as a symbol, not as a record.

**Comment by Linuus** [comment]
Can you show me the code you are trying?

**Comment by Linuus** [comment]
Also, are you using an old version of Pundit? Please update if so.

**Comment by Linuus** [comment]
Closing. Please reopen if you still have problems.
