### ISSUE TITLE
Policy Class in Policy Scope

### ISSUE THREAD

**Issue by kayakyakr** [varvet/pundit#557]
Pretty simple: you can do `authorize record, policy_class: CustomPolicy`, but not `policy_scope(Class, policy_class: CustomPolicy)`

Just a bit of missing functionality that'd be nice to have.

**Comment by Linuus** [comment]
Why would you want to do that?

**Comment by Linuus** [comment]
Did you mistype? Do you want to do this?

```ruby
policy_scope(scope, policy_scope_class: CustomPolicy::Scope)
```

**Comment by kayakyakr** [comment]
That would work too. More specific. But the assumption that `CustomPolicy::Scope` exists would be sufficient to use `policy_class` rather than `policy_scope_class` as well.

**Comment by Linuus** [comment]
I like the explicitness here with `policy_scope_class` and since it's already implemented I'm closing this issue.

Thanks!

**Comment by kayakyakr** [comment]
>_< didn't see the `policy_scope_class` in the readme or code. whoops. sorry for the distraction.

**Comment by Linuus** [comment]
No worries :)

**Comment by cheerfulstoic** [comment]
Is there a reason that `policy_scope_class` isn't available as an option for the `Pundit.policy_scope` method?  I'm trying to unit-test the scope using that method but I can't (as far as I can see) define my own scope...

**Comment by Linuus** [comment]
@cheerfulstoic If you want to unit test the scope, you can call the scope directly:
`FooPolicy::Scope.new(user, @post).resolve`

**Comment by cheerfulstoic** [comment]
Yeah, and that's what I ended up doing, but that's now how I was going to use the scope.  I would have preferred to test it with the same interface that I would have used.  Also, it seems like a weird difference in the API to have the option available in one place and not in another.

But I eventually realized that in my case I don't need to use the two scopes, so I don't care that much at the moment ;)

**Comment by Linuus** [comment]
@cheerfulstoic 

> Yeah, and that's what I ended up doing, but that's now how I was going to use the scope.

How would you have used it, since `Pundit.policy_scope` doesn't support overriding the policy scope class?

Some more info about this can be found in https://github.com/varvet/pundit/issues/537

**Comment by cheerfulstoic** [comment]
That's a good question.  I actually expected to be able to, but I was doing TDD so I started with the tests ;)

Regardless, it feels weird that `pundit` has APIs both on the `Pundit` class and inside of controllers but then suddenly I need to instantiate and call my own scope class if I want to do something different.  Why am I using `pundit` and not just my own class at that point, then?

**Comment by Linuus** [comment]
@cheerfulstoic The main difference is that the `policy_scope` function does more than just return the scope. It also marks it as "scoped" so the `verify_policy_scoped` functionality works. If that was not present the `policy_scope_class` option would probably not be present in that function either.
