### ISSUE TITLE
Update documentation re headless policies (or tweak API for headless policies)

### ISSUE THREAD

**Issue by niborg** [varvet/pundit#558]
[This](https://github.com/varvet/pundit#headless-policies) can be a bit of a trip up. It would be worth indicating that any headless policy must have a second "stooge" attribute just so calls to `policy(:dashboard)` work. Can be as simple as `DashboardPolicy < Struct(:user, :_placeholder_for_dashboard_symbol)`.

Alternatively, it may be worth considering dropping the necessity for a second argument for headless policies, assuming that is feasible.

**Comment by Linuus** [comment]
Fixed in 740cbffd2ff7c529d19f57696da75aca3f3152ab
