### ISSUE TITLE
verify_authorized w/ action_name

### ISSUE THREAD

**Issue by ericsullivan** [varvet/pundit#561]
I have a page that's making multiple ajax calls. I'm working on the specs, and I added verify_authorized to make sure I get all them, but the exception just states the controller name (and the path isn't in the backtrace). Would it be worthwhile to add the action name too? Basically:

```ruby
  def verify_authorized
    raise AuthorizationNotPerformedError, self.class unless pundit_policy_authorized?
  end
```

into

```ruby
  def verify_authorized
    raise AuthorizationNotPerformedError, "#{self.class}\##{action_name}" unless pundit_policy_authorized?
  end
```

That starts assuming it's a rails controller (or one that responds to action_name), so I'm not sure it's worth it (or adding a respond_to guard). I just added the new method to application_controller so it's an easy enough workaround either way.

**Comment by timkrins** [comment]
Not sure I understand fully, but I think this would be up to the individual and what they want to do with the exception.

You could rescue `AuthorizationNotPerformed` in your application controller and then add which ever messages you need (re-raise or do something else - you should have access to what you need)

Check out https://github.com/varvet/pundit#rescuing-a-denied-authorization-in-rails for example on how to do this with a `NotAuthorizedError`

**Comment by ericsullivan** [comment]
I didn't want to rescue the exception just to re-raise the same exception with a slightly more verbose error message, so I added this to my application_controller. I think it's a better default for rails, but not all ruby projects. As you said, it's easy enough to deal with so I'll close this.
