### ISSUE TITLE
Batch load and then authorize

### ISSUE THREAD

**Issue by chadwilken** [varvet/pundit#568]
Quite often we have to authorize a collection of objects that we can't reliably assume was loaded using a `Scope` such as with our GraphQL API. I'm curious if you know of how we could use something like [batch-loader](https://github.com/exAspArk/batch-loader) to load all of the objects at once and then perform our logic on the lazy loaded objects? Any help you can provide would be appreciated.

**Comment by Linuus** [comment]
Can you just iterate over the resources and call `authorize` for each?

**Comment by chadwilken** [comment]
Not with GraphQL Ruby, it has built-in Pundit so you tell each `Type` what policy method to use and it loads the policy and authorizes with that method.

**Comment by Linuus** [comment]
Ok. Sorry, I've never used GraphQL Ruby and the Pundit integration seems to be behind a money wall so I can't help you with that I'm afraid.

Perhaps you can get support from the GraphQL author. I guess that is included if you paid for the library.
