### ISSUE TITLE
Policy lookup on array of objects

### ISSUE THREAD

**Issue by sled** [varvet/pundit#574]
This may be a security concern if not all entities in the array are of the same type. E.g if you have Single-Table-Inheritance models with different policies.

https://github.com/varvet/pundit/blob/290536f71edd0a06670af36193165fe2389bb686/lib/pundit.rb#L147-L149

Possible solutions to this I could think of:

- Ensure all entities are of the same type
- Check each policy for each type of entity

**Comment by Linuus** [comment]
@sled You are not supposed to pass an array of objects you'd like to authorize though. Passing arrays are for when you want namespacing.

See the documentation: https://github.com/varvet/pundit#policy-namespacing
