### ISSUE TITLE
RSpec permission not working as intended

### ISSUE THREAD

**Issue by JalisoCSP** [varvet/pundit#577]
For some time, we've had to replace your existing spec syntax with an each to get it to actually check each permission individually.

For example, the docs say:
```
permissions :update?, :edit? do
  # My tests here
end
```
However, we've noticed that if we change something in `:edit?` that we expect to fail, then the specs still pass.

Say we had 1 test, we would see, eg: `1 examples, 0 failures`, when we'd expect to see `2 examples, 0 failures`, 1 for each `update?` and `edit?`

We'd have to change this to:
```
[:an?, :array?, :of?, :actions?].each do |action|
  permission action do
    # My tests here
  end
end
```
After this change, we'd see `4 examples, 0 failures` as expected.

Has anyone else seen this?

Version: 1.1.0

EDIT: Add version number and expected example results.

**Comment by Linuus** [comment]
@JalisoCSP Can you push a minimal example of this issue that I can test? Also, can you check if the issue is present in the latest version of Pundit?

**Comment by JalisoCSP** [comment]
Hey @Linuus - this also happens in a fresh app with v2.0.1

```
require 'spec_helper'

describe "TestingPolicy", type: :policy do
  permissions :new?, :create, :edit?, :update? do
    it "runs the test" do
      expect(1).to eq(1)
    end
  end
end
```
1 example, 0 failures

```
require 'spec_helper'

describe "TestingPolicy", type: :policy do
  [:new?, :create, :edit?, :update?].each do |action|
    permissions action do
      it "runs the test" do
        expect(1).to eq(1)
      end
    end
  end
end
```
4 examples, 0 failures

**Comment by JalisoCSP** [comment]
I've added this repo incase it helps:

**Comment by JalisoCSP** [comment]
@Linuus I've archived my example repo, as I'm not getting security dependency emails.

Let me know if you need anything else from me. Thanks for your time :)

**Comment by Burgestrand** [comment]
> However, we've noticed that if we change something in :edit? that we expect to fail, then the specs still pass.

The following example code seems to work, so maybe this was fixed?

```ruby
require "bundler/inline"

gemfile do
  source "https://rubygems.org"

  gem "pundit"
  gem "rspec"
  gem "pry"
  gem "set"
end

require "rspec/autorun"
require "pundit/rspec"
require "active_support/all"

class TestingPolicy
  def initialize(*)
  end

  def new?
    true
  end

  def edit?
    false
  end

  def update?
    true
  end
end

class User
end

class Post
end

describe TestingPolicy, type: :policy do
  subject { described_class }

  permissions :new?, :edit? do
    it "runs the test" do
      expect(subject).to permit(User.new, Post.new)
    end
  end

  permissions :new?, :update? do
    it "runs the test successfully" do
      expect(subject).to permit(User.new, Post.new)
    end
  end
end
```

```zsh
❯ ruby example.rb
F.

Failures:

  1) TestingPolicy new? and edit? runs the test
     Failure/Error: expect(subject).to permit(User.new, Post.new)
       Expected TestingPolicy to grant new? and edit? on #<Post:0x0000000132c2ae10> but edit? was not granted
     # example.rb:44:in `block (3 levels) in <main>'

Finished in 0.00791 seconds (files took 0.29876 seconds to load)
2 examples, 1 failure

Failed examples:

rspec example.rb:43 # TestingPolicy new? and edit? runs the test
```

**Comment by dgmstuart** [comment]
@JalisoCSP Also note that the semantics of a test case are "does this work for _all_ of these permissions", so this example you gave is correct in only showing one success:

```ruby
require 'spec_helper'

describe "TestingPolicy", type: :policy do
  permissions :new?, :create, :edit?, :update? do
    it "runs the test" do
      expect(1).to eq(1)
    end
  end
end

# => 1 example, 0 failures
```
