### ISSUE TITLE
Using contexts in rails-api engines does not always work as intended

### ISSUE THREAD

**Issue by Pharserror** [varvet/pundit#580]
### Background

I have a Rails-api app structured like so
```
root-dir
| - engines
  | - my_engine
    | - app
      | - contexts
        | - my_engine
          | - my_context.rb
      | - controllers
        | - my_engine
          | - application_controller.rb
          | - resource_controller.rb
      | - policies
        | - my_engine
          | - resource_policy.rb
```

my_context.rb
```ruby
module MyEngine
  class MyContext
    attr_reader :resource, :user
    def initialize(user, context_resource)
      @context_resource = context_resource
      @user = user
    end
  end
end
```
application_controller.rb
```ruby
require 'pundit'
module MyEngine
  class ApplicationController < ApplicationController::Base
    include Pundit
    def current_user
      # do some stuff with JWT to get the user; I left some stuff out for brevity
      @user = User.find_by_id(JWTWrapper.decode(params[:token])&.dig('user_id'))
      sign_in @user if @user.present?
      @context = MyContext.new(@user, @context_resource)
      return @context
    end
  end
end
```
resource_controller.rb
```ruby
module MyEngine
  class ResourceController < MyEngine::ApplicationController
    def show
      @resource = Resource.find(params[:id])
      @context_resource = @resource.context_resource
      authorize @resource, :show?
    end
  end
end
```
resource_policy.rb
```ruby
module MyEngine
  class ResourcePolicy
    include PolicyConcerns
    def initialize(context, resource)
      @resource = resource
      @context_resource = context&.context_resource
      @user = context&.user
    end

    def show?
      @context_resource.can_show? && @resource.some_other_check
    end
  end
end
```

### Problem

The problem I run into is a `NoMethodError` `can_show?` for `nil` but, when I put a `binding.pry` in the controller `show` and the `show?` method in the policy and inspect `@context_resource` in the controller in the console, then call `current_user`, then go to the `binding.pry` in the policy: suddenly `@context_resource` is no longer `nil`. I can't figure out why this is happening. Is `@context_resource` being garbage collected before the `show?` method in the policy can be called? Has anyone else experienced this?

**Comment by Pharserror** [comment]
may have figured this out. I believe returning the context from `current_user` instead of doing
```ruby
def current_user
  @user = get_user_from_whatever
end

def pundit_user
  Context.new(current_user, @resource)
end
```
may have been the problem. If anyone can confirm feel free to close; otherwise, I will close as soon as I can confirm.

**Comment by ingemar** [comment]
Side note: You should do a basic memoization of `@user`, otherwise the instance variable will get overwritten every time when you call `#current_user`, i.e.

**Comment by Linuus** [comment]
This looks like it's solved. Closing.
