### ISSUE TITLE
how to get authorize return true or false?

### ISSUE THREAD

**Issue by insub** [varvet/pundit#584]
i had user_not_authorized & null_authorized method  on application_controller.rb

```
def user_not_authorized
    respond_to do |format|
      format.html { redirect_to "/422", alert: "No authorize" }
      format.json { render :json => { :success => false, :msg => "No authorize", :data => {}} }
    end
  end

  def null_authorized
    respond_to do |format|
      format.html { redirect_to "/422", alert: "Null authorize" }
      format.json { render :json => { :success => false, :msg => "Null authorize", :data => {}} }
    end
  end
```
it handle not authorized by defalut.
but sometime  i want to handle the not_authorized/null_authorized different. so i try get authorized result， code like that :

```
def show
  if authorize @project, :member?
    do something...
  end
end
```
but it not work. 
what is the right way?

**Comment by jdno** [comment]
`authorize` raises a `Pundit::NotAuthorizedError` if a user has no permission to perform a certain action. It will never return `true` or `false`.

What you are probably looking for is the `policy` method to get the correct policy, and ask it if the user is a member:

```ruby
def show
  if policy(@project).member?
    # do something...
  end
end
```

**Comment by insub** [comment]
@jdno get it! Thank you~
