### ISSUE TITLE
Authorizing & Scoping a collection?

### ISSUE THREAD

**Issue by ttrmw** [varvet/pundit#595]
For actions affecting collections, Pundit can answer two questions:

- `authorize` - Can the user perform this action?
- `policy_scope` - Against which items can the user perform the action?

However, it seems clunky use both methods in the same controller action....

`authorize policy_scope(Model)`

This seems kind of clunky and repetitive - my feeling is that I'll always want to perform both together. 

Hopefully, the Scope as implemented should exclude any resources the user shouldn't be able to see/action upon, so I had considered using only the `policy_scope` method to achieve what I wanted here, but there will be cases where the user might be unauthorized, in which case I'd want to see a 401.

What's the right way to achieve this? I think I want both behaviours but dislike the repetition.

**Comment by Linuus** [comment]
I would probably just do this, if we are talking about an index action for instance:

```ruby
authorize Model
@models = policy_scope(Model)
```

The benefit of this is that if the user is not authorized to access this endpoint, you never even hit the DB. Why query for stuff in the DB if the user is not even authorized to manage them?

**Comment by sedubois** [comment]
> Why query for stuff in the DB if the user is not even authorized to manage them?

Isn't this solved by reversing the nesting?

```rb
policy_scope(authorize Model)
```

It would be great to have a Pundit method which combines those 2 calls (e.g. `authorize_and_scope`). Or maybe even update the plain `authorize` method definition to call `policy_scope` as well?
