### ISSUE TITLE
Pundit version 2.1.0

### ISSUE THREAD

**Issue by marciojg** [varvet/pundit#613]
Hello, 

At [rubyGems](https://rubygems.org/gems/pundit) the last version of pundit is **v2.1.0 of August 14, 2019** but at [repository ](https://github.com/varvet/pundit/releases/tag/v2.0.1) the last version is **v2.0.1 of January 18, 2019**

https://rubygems.org/gems/pundit
https://github.com/varvet/pundit/tags

It's rigth?

Thanks

**Comment by Linuus** [comment]
I think @dgmstuart released 2.1.0. Perhaps he forgot to create a release here at Github and add a tag?

**Comment by dgmstuart** [comment]
Sorry about this! 
I did forget to push the tag. 
I didn't know releases were a thing - I'll have a look at that.

**Comment by dgmstuart** [comment]
Ah cool - pushing the tag seems to have created the release. I'll close this, but please reopen if there's something else I missed.

**Comment by Linuus** [comment]
Phew. I got a bit worried at first with all the rubygem hacks/malware issues lately 😅

**Comment by marcioJesus** [comment]
@Linuus I remembered the same thing :) 
@dgmstuart Thanks!
