### ISSUE TITLE
translate this article into Japanese

### ISSUE THREAD

**Issue by t1gerk1ngd0m** [varvet/pundit#629]
Hello, I'm Japanese and I want to translate this article into Japanese, but unauthorized translation is against copyright. So, I want to allow transition.
I am going to post an article on [Qiita](https://qiita.com/). My purpose is not for commercial purposes, but for my study.

**Comment by ingemar** [comment]
@t1gerk1ngd0m 

よう! 

Nice!  ... But what article are you talking about? The `README.md` file?

**Comment by t1gerk1ngd0m** [comment]
@ingemar Yes! I mean `README.md`!

**Comment by ingemar** [comment]
@t1gerk1ngd0m 

As an employee of **Varvet**, I hereby grant you the permission to **translate** the `README.md` file to **Japanese** and publish it on `qiita.com`.

**Comment by t1gerk1ngd0m** [comment]
@ingemar Thanks!!
