### ISSUE TITLE
Rescuing a denied Authorization in Rails fails

### ISSUE THREAD

**Issue by belgoros** [varvet/pundit#631]
It seems like rescuing a denied Authorization in Rails as explained the [corresponding README section](https://github.com/varvet/pundit#rescuing-a-denied-authorization-in-rails):
```
# application_controller.rb
...
rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  private

  def user_not_authorized
    flash[:alert] = "You are not authorized to perform this action."
    redirect_to(request.referrer || root_path)
  end
```
fails with `ActionController::UnpermittedParameters` exception in the below `PostsController#update` action where the filter of strong parameters is imlplemented as follows:
```
# posts_controller.rb#update

 def update
    respond_to do |format|
      if @post.update_attributes(permitted_attributes(@post))
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end


private

private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :body)
    end
``` 
I had to add `ActionController::UnpermittedParameters` to the above resque clause as follows to make it work:
```
rescue_from Pundit::NotAuthorizedError, ActionController::UnpermittedParameters, with: :user_not_authorized
...
```
I also had to add the below config setting to `application.rb`:
```
config.action_controller.action_on_unpermitted_parameters = :raise
```
to make it work. Is it correct or am I missing something?

Used with
- Rails `5.2.3.`
- ruby `2.6.5`

The code of an example app could be found [here](https://github.com/belgoros/pundit-rails).

**Comment by dgmstuart** [comment]
@belgoros Thanks for the issue. I've run your example app and I haven't been able to reproduce the issue.

Could you please add the following:
1. Set up the example app in a state that will fail (eg. currently nothing is actually being authorized)
2. Provide step-by-step instructions for how to reproduce the error in the test app. 

Here's what I did:
1. Add `authorize @post` at the beginning of `PostsController#update`
2. Change `PostPolicy#update?` to return `false` to simulate a failed authorization
2. remove `ActionController::UnpermittedParameters` from `rescue_from`
3. Click "edit" on a post
4. Click "update":
![Screenshot 2019-12-06 at 16 56 21](https://user-images.githubusercontent.com/393167/70336415-638bb180-1849-11ea-93ae-76d6d3b0bec2.png)

**Comment by belgoros** [comment]
@dgmstuart I followed your steps to put the app in the failing state (see the [latest](https://github.com/belgoros/pundit-rails/commit/5cca39616184ece0ce3ed77112b2e3abaafba3c5) commit), i.e:
- removed `ActionController::UnpermittedParameters` from the rescue clause
- added `authorize @post` in the beginning of the `PostsController#update` action
- commented out `update?`  method in the `PostPolicy` (the one from the parent class will return `false`)

When being a guest user (it is [defined](https://github.com/belgoros/pundit-rails/blob/master/app/controllers/application_controller.rb#L9) in `application_controller`), I could be able to update the `body` attribute:
```ruby
# post_policy.rb
...
def permitted_attributes
    if user.admin?
      [:body, :title]
    else
      [:body]
    end
end
```
Unfortunately, it failed:
<img width="351" alt="Screenshot 2019-12-06 at 17 14 39" src="https://user-images.githubusercontent.com/83579/70338261-e3674b00-184c-11ea-8344-e08f83927de0.png">

**Comment by dgmstuart** [comment]
If you commented out `update?` then isn't this exactly what should happen? If `update?` is false by default, then no users are authorized to perform the action, right?

**Comment by dgmstuart** [comment]
Maybe there's a misunderstanding here: `permitted_attributes` has got nothing to do with authorization at all: it's just a convenient way of managing strong parameters.

**Comment by belgoros** [comment]
@dgmstuart As you can see, `PostPolicy#update?` is [already](https://github.com/belgoros/pundit-rails/blob/master/app/policies/post_policy.rb#L3) commented.
The main purpose is to make it possible:
- `:guest` users to update a post `body` attribute only, not its `title`
- `:admin` to update both a post `title` and `body`.

**Comment by dgmstuart** [comment]
@belgoros see my post above: `permitted_attributes` has got nothing to do with authorization. The way the app is set up, no user (guest or admin) can update posts, because `update?` is always `false`. 

`permitted_attributes` only manages strong parameters: it doesn't override the authorization.

Does that make sense at all?

**Comment by belgoros** [comment]
Ah, yes, I see. `ApplicationPolicy#update?` returns `false by default. So, in my case, if I want both `admin` and `guest` to be able to update, I have to override it the `PostPolicy`  as follows (was commented previousely):
```ruby
def update?
  user.admin? || user.guest?
end
```
I believed that by default, everyone was granted access, but it is the opposite. Thank you, I'll close the issue.

**Comment by dgmstuart** [comment]
@belgoros No problem. Let me know if you have more questions :)
