### ISSUE TITLE
Question: can policy_scopes be applied inside a chain?

### ISSUE THREAD

**Issue by swedishpotato** [varvet/pundit#632]
In a view or form, I want to limit the records show to the user by using the respective pundit policy_scope for those types of records.

For example, let's say a Permisson has many Roles through RolePermissions, and that a Role has many Permissons through RolePermissions.

I also have a  policy_scope on Roles so that not all of them are returned.

In a view or in a form's select statement, how do I limit the Roles shown using the policy_scope for a particular Permission?

The code:

```Permission.first.roles``` 

gives you all roles for that permission, naturally, but I need something like:

```Permission.first.policy_scope([:admin, Role])```

So that the roles linked to that permission are narrowed by the pundit policy_scope for Roles.

Is this possible and if so, what is the syntax? What I am currerntly doing is applying the same limiting scope that Pundit uses manually in the forms and views, but this means if the policy changes, I need to change it in several places in the app, rather than in just the policy.

Pundit is great and I am sure I am simply missing something here! Any help greatly appreciated!

**Comment by dgmstuart** [comment]
Have you tried `RolePolicy::Scope.new(current_user, Permission.first.roles).resolve`?

Check out the example at the bottom of the https://github.com/varvet/pundit#scopes section

**Comment by swedishpotato** [comment]
Thanks - worked perfectly! Damn this Pundit is good! :)

**Comment by dgmstuart** [comment]
Glad it worked for you!
