### ISSUE TITLE
Doc: Is the README wrong, or am I having a massive brainfart?

### ISSUE THREAD

**Issue by rlue** [varvet/pundit#649]
From the README (emphasis mine):

> Like with the authorize method, you can also override the policy scope class:
>
> ```ruby
> def index
>   # publication_class => Post
>   @publications = policy_scope(publication_class, policy_scope_class: PublicationPolicy::Scope)
> end
> ```
>
> Just as with your policy, this will **automatically infer that you want to use the `PostPolicy::Scope` class**, it will instantiate this class and call resolve on the instance. In this case it is a shortcut for doing:
>
> ```ruby
> def index
>   @posts = PostPolicy::Scope.new(current_user, Post).resolve
> end
> ```

What automatic inference is going on here? Based on my understanding of this section in context, it seems like it _should_ say:

> Just as with your policy, this will manually override the scope class used for this query. In this case it is a shortcut for doing:
>
> ```ruby
> def index
>   @publications = PublicationPolicy::Scope.new(current_user, Post).resolve
> end
> ```

Is that correct, or am I missing something?

**Comment by Linuus** [comment]
Looks like you are correct 👍 

PR? :)

**Comment by frenkel** [comment]
@Linuus this was fixed by the PR you merged earlier, so it can be closed :tada:

**Comment by rlue** [comment]
I'll handle it :)
