### ISSUE TITLE
Question: Roles & Pundit, knowing all permission space?

### ISSUE THREAD

**Issue by nitsujri** [varvet/pundit#692]
### Question

My question is: As a role manager, how do I know what permissions/abilities are available to pick from to give to the role? Ideally, I could "pick from" a list of all possible permissions, but I don't fully understand how to get at "all possible permissions".

What's the standard way of handling this?

### Background

Our little admin area is growing and we're currently effectively defining roles inside our policies:

``` ruby
SensitiveDashboardPolicy
  def index?
    @user.auditor?
  end
```

But of course as multiple roles gain access to the same object in a mickey mouse venn diagram, it becomes more ideal assign roles the permissions at the DB level than manually defining which roles has which permissions:

``` ruby
SensitiveDashboardPolicy
  def index?
    @user.has_permission?('view_sensitive_dashboard') # @user has a `sensitive_dashboard` role which has `view_sensitive_dashboard` permission.
  end
```

Apologies if this isn't the right way to go about asking this question.

**Comment by dgmstuart** [comment]
Thanks for the question. This isn't something which Pundit can help with: we don't have a concept of user roles. There are other libraries which can probably be used in addition to pundit which might be able to give you the functionality you're looking for. Here's a good place to start looking: https://www.ruby-toolbox.com/search?q=roles

**Comment by januszm** [comment]
I may be wrong but I think there's a small misunderstanding here. I was looking for information on how to show all permissions user has based on the Pundit policies definitions. E.g.  `Pundit.list_all_policies_and_permissions => [post: [:show, :create, :destroy, ...]]`

**Comment by januszm** [comment]
@dgmstuart  thanks for quick reply, yeah trying to work out which methods are policies which come from Ruby it's nearly impossible, even if we try to put them in a subclass that inherits from BasicObject or similar solution.

I guess the way to go is to write a thin wrapper on top of Pundit that somehow registers what policies are defined

**Comment by dgmstuart** [comment]
@januszm looking at your question again I'm no longer confident I understand what you're asking for. You say: 

> "show all permissions _user_ has"

...but I don't understand what that can possibly mean:

If the user is involved then there's no fixed answer: a policy rule is a method that is evaluated at runtime for a specific combination of user _and_ record: it doesn't have a fixed answer for a given user. 

Since it's an arbitrary method, it doesn't even need to return a fixed answer for a given combination of user and record - this for example is valid (if unrealistic) and returns a different result every second:

```ruby
class WidgetPolicy < ApplicationPolicy
  def show?
    Time.now.seconds_since_midnight.to_i.even?
  end
end
```

**Comment by januszm** [comment]
@dgmstuart  what I meant is a way to list all policies for a given policy class, or a list of all policies from all classes for a given user context, that could be returned to an external frontend/UI application or another client.

eg.
```ruby
HomePolicy.all(user_context)
# => { index?: true, edit?: false }
# or
PunditPolicy.all(user_context)
{
  home: { index?: true, edit?: false }
}
```
and so on

**Comment by dgmstuart** [comment]
@januszm what do you mean by `user_context`?

**Comment by dgmstuart** [comment]
@januszm consider this policy:


```ruby
class HomePolicy
  def initialize(user, record)
    @user = user
    @record = record
  end

  def show?
    @record.user_id = @user.id # users can only see their own records
  end 

  def edit?
    show? && Time.current.hour < 10 # no edits after 10am
  end
end
```

What is your expected output for `PunditPolicy.all(user_context)`?

**Comment by januszm** [comment]
@dgmstuart  I'm sorry I wasn't clear, by the user context  I mean user and  domain model/record.

> What is your expected output for PunditPolicy.all(user_context)?

```
# record.user == user, 4PM
{  home: { show?: true, edit?: false }  }

# record.user == user, 9AM
{  home: { show?: true, edit?: true }  }

# record.user != user
{  home: { show?: false, edit?: false }  }
```

this way other clients, like frontend, know when to show the edit button in a potential UI, via an API that can be build around this feature

**Comment by dgmstuart** [comment]
@januszm Ah I see. I think your best bet is to have the API layer control which permission rules are requested by your UI and just duplicate the information about what policy rules exist there? 

...and then make sure that you somehow have a check that all the permission rules are actually defined on the policies (maybe that's just covered by your regular request specs?).

What you expose on the API will probably be a subset of all the permission rules anyway, since with the generated `ApplicationPolicy` every Policy has eg. a `delete?` permission, even for resources which don't define a `delete` action, so it's probably not meaningful to expose `delete?: false` for those resources?

Best of luck!

**Comment by januszm** [comment]
@dgmstuart yes I'm going to build an API but I just wanted to double check if the code duplication can be avoided. There will have to be some kind of spec or maybe even a Rubocop Cop similar to https://docs.rubocop.org/rubocop-rails/cops_rails.html#railslexicallyscopedactionfilter that verifies that method defined in the API exists in policies and/or vice versa

**Comment by RadoslawT** [comment]
> You could try to roll your own solution - part of that would involve doing a bit of introspection and metaprogramming on the Policy objects to work out which methods are the policy permissions and which are eg. helper methods.

Maybe someone will find it helpful, fetching existing policies for the `FooPollicy` should be doable with something like:
```ruby
(FooPolicy.instance_methods - Object.instance_methods).grep /.*\?/
```

**Comment by dgmstuart** [comment]
@RadoslawT That's a good start, but there are two issues:

1. Helper methods defined on `FooPolicy` or `ApplicationPolicy` would also show up in that list
2. If you're using an `ApplicationPolicy` which defines all the CRUD actions, then this list will include actions which don't actually exist for the current resource (not just that the user doesn't have permission to do them, but that the action doesn't make sense at all)

**Comment by januszm** [comment]
Thanks for sharing @RadoslawT !

@dgmstuart  right, but this might be good enough actually. As long as you avoid ending helper methods with `?` it'll still work. And regarding methods from the Application policy, as this is the base class, they're anyway included in all child classes, so I think it still makes sense, I'm thinking about the potential API which I mentioned above, if the API only returns permissions, that the user has, all methods from the Application Policy that return 'false' would be filtered out anyway.

**Comment by dgmstuart** [comment]
On my team all our helper methods are booleans with a `?`, but if you have different conventions then I can see how that would work for you!
