### ISSUE TITLE
Use of Struct in Headless Policies

### ISSUE THREAD

**Issue by drewmoore** [varvet/pundit#696]
Thanks for this great gem! When trying to implement a headless policy, rubocop advised [against this](https://rubystyle.guide/#no-extend-struct-new). When experimenting on my own machine, I actually found it possible to avoid the usage of `Struct` altogether and instead just use the exact same pattern as for our ActiveRecord models' policies. This also works for me in views using `if policy(:my_resource).show?`. I'm wondering if Struct is needed, and if not, if the documentation could be updated to reflect this. Thanks!

Ruby version: 2.7.3
Pundit version: 2.1.1

**Comment by dgmstuart** [comment]
Just came here to raise the same thing. 

There's also [a good blog post from The Pug Automatic](https://thepugautomatic.com/2013/08/struct-inheritance-is-overused/) going into this in some detail.

**Comment by dgmstuart** [comment]
@drewmoore could you expand on what you mean by "instead just use the exact same pattern as for our ActiveRecord models' policies."?

**Comment by dgmstuart** [comment]
@drewmoore We've discussed this and concluded that there isn't a particular reason to use Struct. We'd happily accept a PR which changes the documentation to a different approach if you have something specific in mind.

**Comment by drewmoore** [comment]
> @drewmoore could you expand on what you mean by "instead just use the exact same pattern as for our ActiveRecord models' policies."?

Oh yes, I just meant that we are able to declare our headless policies in exactly the same manner as any other type of policy. I provided a documentation update on #717.

**Comment by dgmstuart** [comment]
Closed by #171
