### ISSUE TITLE
Solve depreciations in rubocop.yml

### ISSUE THREAD

**Issue by MarceloAGuimaraes** [varvet/pundit#701]
I was trying to solve some issues on Pundit, but my rubocop keeps failing because of wrong syntax and depreciations on rubocop config file.
Because of this, i can't go through some issues. This issue for example: https://github.com/varvet/pundit/issues/691.

This screenshot show some problems: 
<img width="347" alt="Screen Shot 2022-01-06 at 17 11 20" src="https://user-images.githubusercontent.com/41841441/148474122-2df35429-7936-458e-bf35-7aa0bfeff6da.png">

**Comment by Burgestrand** [comment]
Hi! As I mentioned in https://github.com/varvet/pundit/pull/702#issuecomment-1007318138 there are no deprecations in `rubocop.yml` in the `main` branch. Are you perhaps running a newer version of rubocop on this repository instead of running `bundle exec rubocop`?
