### ISSUE TITLE
Readme docs error

### ISSUE THREAD

**Issue by yserkez** [varvet/pundit#705]
The main readme doc (line:29) suggests to `include Pundit::Authorization` in the `application_controller.rb`, which causes `NameError: uninitialized constant Pundit::Authorization`. The solution is actually in the [api docs](https://www.rubydoc.info/gems/pundit) to just `include Pundit` without ::Authorization.

**Comment by sijiaoh** [comment]
It looks like the README in the master branch is not the latest version.
It is the next version.

![image](https://user-images.githubusercontent.com/60224604/148627229-5ebed829-bcf7-42e4-9671-c8570a871a76.png)

**Comment by Burgestrand** [comment]
Yes, the README in `master` is newer than the most recent version of the Pundit gem. The first link in the table of contents links to the [API documentation](https://www.rubydoc.info/gems/pundit) which should be accurate with the most recently released gem :)
