### ISSUE TITLE
Readme on main branch has outdated instructions

### ISSUE THREAD

**Issue by scarhand** [varvet/pundit#718]
The Installation section in the readme on the main branch instructs you to 
> Include Pundit::Authorization in your application controller

However, all the v2 branches (correctly) instruct you to include _Pundit_.
As someone who just blindly copy-pastes instructions from readme's, it took me some time to figure out what caused the `uninitialized constant Pundit::Authorization` :)

**Comment by Burgestrand** [comment]
Hi! Yes, the README is newer than the most recently released version.

[The first link at the very top of the README](https://www.rubydoc.info/gems/pundit) links explicitly to the API documentation.

**Comment by Burgestrand** [comment]
Hi! I just wanted to let you know I added a note about the README on `main` possibly being different from what's released, I hope this will help reducing future confusion!
