### ISSUE TITLE
authorize went from using policy to policy! in #697

### ISSUE THREAD

**Issue by Burgestrand** [varvet/pundit#730]
> This appears to be a breaking change, and I'm curious whether or not that was intentional. Our code uses the `authorize(record)` method below which [used to find the policy_class with `policy`](https://github.com/varvet/pundit/pull/697/files#diff-2acc48fe8302d7198f5a4aa4aaa8b4f0502d185e186a099283264da056d450c7L221) but this now uses `policy!` in that situation. 
> 
> Can you please verify that you meant to force a more explicit definition of `policy_class`? Thanks!

_Originally posted by @adherr in https://github.com/varvet/pundit/pull/697#discussion_r835656389_

**Comment by dgmstuart** [comment]
I think I'm missing something: wasn't this a bugfix?

In the previous implementation, we were effectively doing `policy = policy(record)` and then calling `policy.public_send(query)`. 

The issue with that is that `policy(record)` returns `nil` in the situation where there's no policy class corresponding to the record, so we'd get eg. `NoMethodError: index? is not defined on nil`?

@adherr What's the behaviour from the previous implementation that you're relying on?

**Comment by Burgestrand** [comment]
Good point! I missed that.
