### ISSUE TITLE
uninitialized constant Pundit::Authorization

### ISSUE THREAD

**Issue by hgsgtk** [varvet/pundit#731]
Hi, I changed from `include Pundit` to `include Pundit::Authorization`, but I got an error: `NameError: uninitialized constant Pundit::Authorization`. Have you ever get such an error before? I'd like to know a way to solve this error.

My code base is:
- Ruby: 2.7.4
- Ruby on Rails: 6.1

Gemfile

```
gem "pundit" 
```

application_controller in Rails.

```ruby
class ApplicationController < ActionController::Base
  include Pundit::Authorization
```

**Comment by Burgestrand** [comment]
Hi!

Are you using latest version of Pundit? Perhaps bundler is using an old version of pundit on your system.

Latest version of pundit is **[2.2.0](https://rubygems.org/gems/pundit/)**. `bundle info pundit` should tell you which version bundit chose for you. You might need to `bundle update pundit`.

**Comment by hgsgtk** [comment]
@Burgestrand Sorry for delaying my response.

```
$ bundle info pundit                                         ‹ruby-2.7.4›
  * pundit (2.2.0)
	Summary: OO authorization for Rails
	Homepage: https://github.com/varvet/pundit
	Path: {$user}/.rvm/gems/ruby-2.7.4/gems/pundit-2.2.0
```

When, I restarted my application, it worked. Sorry for bothering you. Thank you for your quick response 🙇

**Comment by Burgestrand** [comment]
Great! I'm glad you got it to work :)
