### ISSUE TITLE
Unable to find policy when ids are passed to the params

### ISSUE THREAD

**Issue by kouroubel** [varvet/pundit#734]
In my model Expense index view, I have a link_to the expenses#export  that posts the displayed @expenses ids in order to be exported to Excel.

`<%= link_to 'Export', export_expenses_path(:expense_ids => @expenses.pluck(:id), format: :xlsx), method: :post, class:"btn btn-sm btn-outline-export" %>`

The controller action expenses#export looks like this

  ```
def export
    @expenses = Expense.find( params[:expense_ids] )
    
    authorize @expenses

    respond_to do |format|
      format.html
      format.xlsx
    end
  end
```

Finally, in my expense_policy.rb I have this

```
  def export?
    @user.has_role? :admin or @user.has_role? :user or @user.has_role? :viewer
  end
```
 While everything is working OK locally, the application hits an exception in production (Heroku) with the message

**expenses export (Pundit::NotDefinedError) "unable to find policy `Expense::ExpensePolicy`**

and I get the following report from the exception notification gem

![Clipboard01](https://user-images.githubusercontent.com/35150537/167304654-0d52ba5b-292a-40a3-b228-847776f78df8.jpg)

I am guessing this is probably due to the fact that the expense ids are exported in the params and the URL looks like this https://constructionlink2.herokuapp.com/expenses/export.xlsx?expense_ids%5B%5D=2&expense_ids%5B%5D=1.

Is there anything I can do to resolve this issue?

**Comment by Burgestrand** [comment]
I'd guess that [you have namespacing overrides somewhere in your code](https://github.com/varvet/pundit#policy-namespacing), probably something like this in your controller:

```ruby
def authorize(record, query = nil)
  super([:expense, record], query)
end
```

If so then that's probably the reason for your issue.

If that's not the case, then a reproduce example would help a lot! A github repo or gist that we can run that exhibits the problem ☺️

**Comment by kouroubel** [comment]
Thank you for taking the time. `authorize Expense` has solved the issue.
