### ISSUE TITLE
Singular model class name vs. Plural module name

### ISSUE THREAD

**Issue by dpaola2** [varvet/pundit#744]
In our rails app we have a data model with an `Announcement` model. We also have some namespaces business logic objects as part of an `Announcements` module (`Announcements::Create`, etc).

While unit testing our pundit policies today (using https://github.com/ProctorU/policy-assertions) we noticed that we were passing the module name `Announcements` instead of the `Announcement` model class. The tests (incorrectly) passed because pundit seemed to inflect the module's name to match the policy name `AnnouncementPolicy`.

Not a huge deal TBH but wanted to flag it here in case this is either an unforeseen consequence or in case others see this and were equally perplexed as to why the policy is matching the wrong record type as a parameter.

Thanks for all of your hard work on this gem - it's one of my favorites that I keep coming back to over the years. 👍

**Comment by TheDevJoao** [comment]
Hey @dpaola2, I'm currently looking into this issue 👍🏼

**Comment by Burgestrand** [comment]
I tried to replicate this, but I could not. It doesn't appear to singularise `Announcements` to `AnnouncementPolicy`, it just finds nothing.

Closing for now. Feel free to reopen if you have some way of reproducing, or if I simply understood you wrong!

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile do
  source "https://rubygems.org"

  ruby "3.2.2"

  gem "pundit", "~> 2.3"
end

User = Data.define

module Announcements
end

class Announcement
end

class AnnouncementPolicy
  def initialize(user, record)
    @user = user
    @record = record
  end
end

policy = Pundit.policy(User.new, Announcements)
puts "Policy for module: #{policy}"

policy = Pundit.policy(User.new, Announcement)
puts "Policy for model: #{policy}"
```

The output is:
```
❯ ruby example.rb
Policy for module: 
Policy for model: #<AnnouncementPolicy:0x0000000107906a70>
```
