### ISSUE TITLE
generator fails with ruby 3.2.0

### ISSUE THREAD

**Issue by Skulli** [varvet/pundit#755]
`File.exists?` from https://github.com/varvet/pundit/blob/6513071aa790f061dec72e676b99996fa007c9ff/lib/generators/rspec/templates/policy_spec.rb#L1 fails with `undefined method exists? for File:Class`

It was removed with 3.2.0 and deprecated before that. `File.exist?` should be used now.

edit: https://github.com/varvet/pundit/pull/754 exists already

**Comment by johanandre** [comment]
@Skulli i've just finished up the pull request and it is waiting for review/merge.

**Comment by Burgestrand** [comment]
Closing now that #754 is merged.

**Comment by eoinkelly** [comment]
❤️  your work here everybody. It'd be awesome to get a release which includes this soon 🤞

**Comment by deepakmahakale** [comment]
Do we have any plans to release this?
Right now we are using this from GitHub instead of RubyGems due to this fix.

**Comment by Burgestrand** [comment]
Hi @deepakmahakale this has now been released 😊

**Comment by deepakmahakale** [comment]
Thanks 😊
