### ISSUE TITLE
"include Pundit::Authorization" undefined ? 

### ISSUE THREAD

**Issue by zulquairnain-tx** [varvet/pundit#757]
I was using rails 7.0.4.0 when i faced the error "uninitialized constant Pundit::Authorization", I replaced it with "include Pundit" in application_controller and it worked.

**Comment by zulquairnain-tx** [comment]
closed

**Comment by albertski** [comment]
I ran into the same issue.  Should we be using `include Pundit` instead of `include Pundit::Authorization` in Rails 7?

**Comment by albertski** [comment]
Since this issue is closed, I created a new issue: https://github.com/varvet/pundit/issues/798
