### ISSUE TITLE
Authorizing controller actions with no associated model

### ISSUE THREAD

**Issue by pbougie** [varvet/pundit#77]
Pundit looks great for authorizing models but in some instances I need to authorize controller actions (with no associated model) as well. A simple check whether the user is logged in or not will suffice most of the time. However, sometimes the ability to view a controller action is based on a user role, i.e. user can view settings page if administrator but not if regular user.

What are the best practices for these situations? Any clarifications would be appreciated on how all the authorization pieces fit together.

**Comment by Senich** [comment]
Is this feature is available in current gem version? Seems for me it doesn't work properly.
I've still got an error  - "unable to find policy `DashboardPolicy` for `:dashboard`" while I do have dashboard_policy.rb in policies folder.

**Comment by thomasklemm** [comment]
Yes, it is. Maybe you'd need to restart your Rails server to pick up the changes or have a typo either in the file name or class name. Could you check that?

**Comment by Senich** [comment]
I double checked that, there is no typo and of course I restarted server couple times. It's so simple so I have no idea where I screwed up.
**dashboard_controller.rb**

     class DashboardController < ApplicationController
        def index
          authorize :dashboard, :index?
          # skip_policy_scope
        end
      end
**dashboard_policy.rb**

    class DashboardPolicy < Struct.new(:user, :dashboard)
      class Scope < Scope
        def resolve
          scope
        end
      end
  
      def index?
        true
      end
  
    end 
my root path is 'dashboard#index' so when I start my application I get beautiful 
Pundit::NotDefinedError in DashboardController#index
unable to find policy `DashboardPolicy` for `:dashboard`   and again policy is in the policies/dashboard_policy.rb

**Comment by nbekirov** [comment]
Is it `app/policies/dashboard_policy.rb` or `policies/dashboard_policy.rb`?

---

Check this out:
  * If I make a typo in my policy class name like so

  ```ruby
  class DashboardPolicyWrong < Struct.new(:user, :dashboard)
  ```
  The error is as follows: `Unable to autoload constant DashboardPolicy, expected [APP_DIR]/app/policies/dashboard_policy.rb to define it`

  * However if the file is missing (if I move/rename/delete it) the error is `unable to find policy DashboardPolicy for :dashboard`

**Comment by Senich** [comment]
sorry, policy is in the app/policies/ of course
Your example is correct providing pundit can initially see your policy but in my case pundit somehow can't locate that

**Comment by Senich** [comment]
Interesting, in this case I get
`Pundit::PolicyScopingNotPerformedError in DashboardController#index`
and I guess that means pundit at least sees the DashboardPolicy if it informs about missing scope...
As a temporal fix I can use `skip_policy_scope` in `DashboardController#index` as far as every user can see index page but it's not zen though. I'd like to get whats wrong here.

**Comment by thomasklemm** [comment]
`class Scope < Scope` can't work if you're not inheriting from an `ApplicationPolicy` with `Scope` defined. Maybe that's been the cause of the exception.

**Comment by Senich** [comment]
And I can't inherit from ApplicationPolicy because I have no model, but scope is needed for work at the same time

**Comment by thomasklemm** [comment]
Just say `class Scope`, without inheriting it from anywhere.

**Comment by Senich** [comment]
class DashboardPolicy < Struct.new(:user, :dashboard)
  
       class Scope
         def resolve
           scope
         end
       end
  
      def index?
         true
      end
    end   

Still got `Pundit::PolicyScopingNotPerformedError in DashboardController#index`

**Comment by Senich** [comment]
I figured out what was wrong with my code.
I have `after_action :verify_policy_scoped, only: :index`  in my application_controller and because of that Pundit tried to determine scope policy in first place and clearly failed. I just reroute index page to `dashboard#show` action, set ther `authorize :dashboard, :show?` and everything works. Thank you guys!
