### ISSUE TITLE
Hook into Rails generators (scaffold, model) to generate policy classes

### ISSUE THREAD

**Issue by joelzwarrington** [varvet/pundit#785]
I would like pundit policies to be generated when I run Rails generators such as `scaffold` and `model`, instead of having to run `rails generate pundit:policy post` seperately.

I wouldn't mind working on something like this, just want to see if there's appetite for it!

**Comment by Burgestrand** [comment]
That sounds nice. I don't personally use the generators too much, but I'm sure the reduced friction would be appreciated by those who do.

I'm sure the details are in here somewhere: https://guides.rubyonrails.org/generators.html

**Comment by Burgestrand** [comment]
This looks like a duplicate of https://github.com/varvet/pundit/issues/735 😊

… so I'm closing this in favour of moving the topic there instead!

**Comment by Burgestrand** [comment]
I feel GitHub is rather dismissive with "closed this as _not planned_" which is not really true, it just falls under the umbrella of "duplicate" 😅
