### ISSUE TITLE
README for headless section is incorrect?

### ISSUE THREAD

**Issue by Leee-xx** [varvet/pundit#791]
The readme currently indicates that the headless record argument is the second one passed into `#authorize`, but the example shows it as the being the first arg. I assume it's supposed to be the first?

> Note that the headless policy still needs to accept two arguments. The **second** argument will be the symbol :dashboard in this case, which is what is passed as the record to authorize below.
```
# In controllers
def show
  authorize :dashboard, :show?
  ...
end
```

https://github.com/varvet/pundit#headless-policies

**Comment by Linuus** [comment]
The readme notes that the _policy_ still needs to accept two arguments and the second one is the symbol you pass.

The policy:
```rb
# app/policies/dashboard_policy.rb
class DashboardPolicy
  attr_reader :user

  # `_record` in this example will be :dashboard
  def initialize(user, _record) # two arguments, and the second argument is :dashboard
    @user = user
  end

  def show?
    user.admin?
  end
end
```
