### ISSUE TITLE
uninitialized constant Pundit::Authorization

### ISSUE THREAD

**Issue by albertski** [varvet/pundit#798]
Below is a simplified version of a concern I use in my Controllers.

```
module One
  module Two
    module PunditAuthorization
      extend ActiveSupport::Concern
      include Pundit::Authorization
    end
  end
end
```
When I upgraded to Rails 7, I got the following error:

```
my-engine/controllers/concerns/one/two/pundit_authorization.rb:6:in `<module:PunditAuthorization>': uninitialized constant One::Two::PunditAuthorization::Pundit (NameError)

      include Pundit::Authorization
              ^^^^^^^^^^^^^^^
```

The issue disappears if I use `include Pundit` instead of `include Pundit::Authorization`.  Should we be using `include Pundit::Authorization` in Rails 7?

**Comment by Burgestrand** [comment]
No, `include Pundit` is deprecated and will be removed in a future release.

With the limited information provided my first guess is that you might be using an old version of Pundit.truby

Moving this to discussions.
